### ISSUE TITLE
[Truffle] Provide typings for non-transacting contract function calls

### ISSUE THREAD

**Issue by m-chrzan** [ethereum-ts/TypeChain#104]
Truffle provides a way of calling a contract function in a way that returns the result as if the function call were to be executed against the current blockchain state, but without actually affecting the state. See [here](https://github.com/trufflesuite/truffle/tree/develop/packages/truffle-contract#explicitly-making-a-call-instead-of-a-transaction) for documentation. The Truffle target doesn't currently provide typings for these.

## Expected behavior 1

With the following contract code:
```
uint number;

function setGetNumber(uint n) public returns (uint) {
  number = n;
  return number;
}
```
the following TypeScript should fail to compile:
```
const notANumber = [42]
const greeter = await Greeter.new("", { from: deployer });
await greeter.setGetNumber.call(notANumber)
```
but currently compiles.

## Expected behavior 2

With the following contract code:
```
function getNumber() public pure returns (uint) {
  return 42;
}
```
the following TypeScript should successfully compile:
```
const greeter = await Greeter.new("", { from: deployer });
await greeter.getNumber.call()
```
but currently doesn't.

**Comment by krzkaczor** [comment]
Yeah, I had it somewhere on my todo list. Another thing missing is support for fallback functions but ABI parser is lacking it ATM.

**Comment by ipatka** [comment]
I added and tested this functionality in the above PR

**Comment by krzkaczor** [comment]
I guess, it's done now. If not, please reopen.
