### ISSUE TITLE
Parse the tuple/struct type

### ISSUE THREAD

**Issue by m-chrzan** [ethereum-ts/TypeChain#105]
ABIs can contain functions that take as argument or return tuples (Solidity structs). Granted, I don't think these are yet accessible from web3, but in anticipation of future updates, it would be nice if the parser didn't choke on the following contract code:
```solidity
struct Struct1 {
  uint number;
}

struct Struct2 {
  Struct1 s;
}

Struct2 public s;
```

**Comment by yarrumretep** [comment]
@krzkaczor - I'm working on this now - should have a PR for ya later tonight or tomorrow.
