### ISSUE TITLE
Use DefintielyTyped Typings Instead of `web3-typescript-typings`

### ISSUE THREAD

**Issue by seesemichaelj** [ethereum-ts/TypeChain#110]
There currently is a `@types/web3` now, and it seems to be getting more TLC than [web3-typescript-typings](https://www.npmjs.com/package/web3-typescript-typings). I don't use TypeChain currently, but I just so happened to notice this haha. I do want everyone to start using the same typings so that they can mature, and I believe `DefinitelyTyped` is the right place for that.

**Comment by krzkaczor** [comment]
`web3-typescript-typings` is used b/c we needed typings for 0.20.x version. AFAIK `@types/web3` supports 1.0.0

I am gonna close it for now, please reopen if I am wrong.

**Comment by seesemichaelj** [comment]
Ah sorry about that; you are correct
