### ISSUE TITLE
Truffle.Contract does not extend Truffle.ContractNew

### ISSUE THREAD

**Issue by roderik** [ethereum-ts/TypeChain#113]
While this works if you use the Deployer, it does not in tests where you want to use .new to setup beforeEach sets. We build a smart contract library and our migrations in this library are empty

We end up with methods like:

```
export async function deploy<Contract extends Truffle.Contract<any>>(
  contract: Contract,
  params: any[],
  deployer?: Truffle.Deployer
) {
  if (deployer) {
    await deployer.deploy(
      (contract as unknown) as Truffle.ContractNew<any[]>,
      ...params
    );
    return contract.deployed();
  }
  return ((contract as unknown) as Truffle.ContractNew<any[]>).new(...params);
}
```

**Comment by krzkaczor** [comment]
@roderik could you give us some repro code? `.new` is already part of a `Contract` typings. See: https://github.com/ethereum-ts/TypeChain/blob/master/test/integration/targets/truffle/test/DumbContract.ts#L7

**Comment by roderik** [comment]
Yes, new is defined in every contract, but not on the top Contract level. (see the generic in the deploy function)

From truffle-typings:
```
  interface Contract<T> {
    deployed(): Promise<T>;
    at(address: string): T;
  }

  interface ContractNew<ARGs extends any[]> {
    "new"(...args: ARGs): any;
  }
```

Contract should extend ContractNew
