### ISSUE TITLE
ethers.js target doesn't support extra ethers options

### ISSUE THREAD

**Issue by snario** [ethereum-ts/TypeChain#118]
e.g., `contract.function.foo(arg1, arg2, { gasLimit: 5e6 })` does not correctly type

**Comment by PhABC** [comment]
Any ETA  for this?

**Comment by andrevmatos** [comment]
I think this is fixed. `ethers` target `functions` receive as last parameter an optional `TransactionOverrides` object (defined at contract's `index.d.ts`), which does exactly what this issue describes.

**Comment by krzkaczor** [comment]
@snario @PhABC could you verify that it's already fixed?

**Comment by PhABC** [comment]
Looks fine now indeed!
