### ISSUE TITLE
Add support for return types that are structs

### ISSUE THREAD

**Issue by snario** [ethereum-ts/TypeChain#119]
If I have something like...

```solidity
contract C {
    struct Bar {
        address foo;
        uint256 baz;
    }

    function fun() returns (Bar) { ... }
}
```

Then the typing of `C.functions.fun()` is `Promise<object[]>;`.

**Comment by krzkaczor** [comment]
I think that some targets already support it. Once we unify tests between targets i will create nice compatibility table 👍
