### ISSUE TITLE
ethers: bytes argument generating the wrong type

### ISSUE THREAD

**Issue by pkieltyka** [ethereum-ts/TypeChain#123]
great project and works quite well with ethers v4

however, for a function declaration like `function safeTransferFrom(address _from, address _to, uint256 _id, uint256 _amount, bytes _data)` typechain for ethers generates the following declaration:

```typescript
    safeTransferFrom(
      _from: string,
      _to: string,
      _id: number | string,
      _amount: number | string,
      _data: (string)[]
    ): Promise<ContractTransaction>;
```

the `_data: (string)[]` argument is wrong, and should be: `_data: Uint8Array`

**Comment by krzkaczor** [comment]
Thanks for the report! I think we are gonna remove ethers target because AFAIK @ricmoo implemented type generator as a part of ethersjs CLI. Can someone confirm it?

**Comment by pkieltyka** [comment]
oh? as far as I now, ethers-cli is a deploy tool, not really a typescript declaration generator from an abi -- but maybe there's a separate tool somewhere

**Comment by ricmoo** [comment]
I haven’t pushed it yet, because it does support tuples yet. Should I push it now and worry about tuples later?

**Comment by ricmoo** [comment]
(maybe after adding the tuple type to human-readable ABI?)

**Comment by pkieltyka** [comment]
@ricmoo no harm is pushing it early and just noting tuples support is coming, and make an issue in there about it..

**Comment by snario** [comment]
+1 would love to try this @ricmoo

**Comment by dhl** [comment]
Would love to see the declaration generator released also, especially if TypeChain is going to phase out support for ethers.js.

**Comment by ricmoo** [comment]
I spent today porting ethers to try using lerna, which I’m liking so far. :)

I’ll try to get my tool released in the `next` branch of ethers-cli tomorrow. :)

**Comment by snario** [comment]
@ricmoo do you have an example of usage?

**Comment by quezak** [comment]
Any update on this?
BTW: the culprit here looks to be in [parsing the evm types](https://github.com/ethereum-ts/TypeChain/blob/d62a31df81aba7554e08a6f7016cab0a2766e94a/lib/parser/typeParser.ts#L82) -- `bytes` actually gets interpreted as `bytes1[]`, hence in ethers output it's mapped to `string[]`. Isn't this interpretation wrong in the first place? IMHO `bytes` should be mapped to `Buffer | Uint8Array` or something.

```
    case "bytes":
return new ArrayType(new BytesType(1));
```

**Comment by krzkaczor** [comment]
This is exactly how it's being parsed: https://github.com/ethereum-ts/TypeChain/blob/master/lib/parser/typeParser.ts#L83 This could be somehow connected to: https://github.com/ethereum-ts/TypeChain/issues/98

**Comment by ricmoo** [comment]
Have you looked into the v5 cli yet for TypeScript?

https://github.com/ethers-io/ethers.js/blob/ethers-v5-beta/packages/cli/src.ts/bin/ethers-ts.ts

It supports tuples and should work for most contracts. I’ll be fixing the cli up a bit more this week too. It takes Solidity contracts and spits out a single TypeScript file of classes which inherit from Contract, and expose the ContractFactory and ABI.
