### ISSUE TITLE
truffle: There is no eventGenerator

### ISSUE THREAD

**Issue by saltylight** [ethereum-ts/TypeChain#128]
```
function generateContractInstanceInterface(c) {
    return `
export interface ${c.name}Instance extends Truffle.ContractInstance {
  ${c.constantFunctions.map(generateConstantFunction).join("\n")}
  ${c.functions.map(generateFunction).join("\n")}
  ${c.constants.map(generateConstants).join("\n")}
}
  `;
}
```

If you see `truffle/generation.js`, you cannot find Event mapping.
I think event mapping code such as 
`${c.events.map(generateEvents).join("\n")}`
need to be inserted.

**Comment by krzkaczor** [comment]
Yup, events are missing right now in Truffle target. I will try to get Gitcoin funding for this.

**Comment by krzkaczor** [comment]
It's done in v2
https://github.com/ethereum-ts/TypeChain/releases/tag/v2.0.0
