### ISSUE TITLE
Wrong big number instance type

### ISSUE THREAD

**Issue by featherbits** [ethereum-ts/TypeChain#136]
Generated types references bignumber.js but in reality bn.js is used by ethereum.

**Comment by sebastianst** [comment]
I also propose to change all instances of `BigNumber` in the generated `truffle-contracts` to `BN` for truffle types generation after https://github.com/ethereum-ts/truffle-typings/pull/7 has been merged.

**Comment by krzkaczor** [comment]
Are you talking about `web3-1.0.0` target? which version of web3 do you use exactly?

**Comment by featherbits** [comment]
Target was truffle. Not sure exactly any more which version it was.

**Comment by sebastianst** [comment]
For me: node `v11.9.0`, web3 `1.0.0-beta.43`, typescript `3.3.1`, truffle `v5.0.2` and truffle-typings `1.0.6`.

**Comment by jaredswarts55** [comment]
Where is this at? Is this now completed because of ethereum-ts/truffle-typings#7? it does declare import BN.

**Comment by krzkaczor** [comment]
It's still not addressed AFAIK. @jaredswarts55 feel free to contribute if you have time.

**Comment by krzkaczor** [comment]
Should be fixed in v2. Releated; https://github.com/ethereum-ts/TypeChain/issues/211

https://github.com/ethereum-ts/TypeChain/releases/tag/v2.0.0
