### ISSUE TITLE
Returned structs have wrong types

### ISSUE THREAD

**Issue by sebastianst** [ethereum-ts/TypeChain#139]
If a contract function returns a struct, TypeChain declares the return type to have `BigNumber`/`BN` fields, where `uint`s are in the struct. This is the intuitive behaviour. Unfortunately, returned structs have all fields converted to `string`s first.

Related #119 #136 

Target: truffle
Versions: typescript `3.3.1`, node `v11.9.0`, web3 `1.0.0-beta.43`, truffle `v5.0.2` and truffle-typings `1.0.6`.

**Comment by krzkaczor** [comment]
This should be done in v2. If not, we need repro.

https://github.com/ethereum-ts/TypeChain/releases/tag/v2.0.0
