### ISSUE TITLE
Vyper support

### ISSUE THREAD

**Issue by gakonst** [ethereum-ts/TypeChain#146]
It would be nice if TypeChain supported type bindings for Vyper

https://github.com/ethereum/vyper/tree/master/vyper/types

**Comment by krzkaczor** [comment]
@gakonst I always thought that vyper generates regular ABI files (same standard as solc). What's the difference?

**Comment by gakonst** [comment]
Ah, totally missed the fact that I provide the ABI json and not the source code. NVM.

**Comment by FormidablePencil** [comment]
Would you mind a question? How would you get TypeChain to generate types for Vyper contracts? Thanks in advance.

**Comment by krzkaczor** [comment]
@FormidablePencil you need to get ABI files from Vyper compilation results. If you use vyper with Hardhat, just use typechain-hardhat plugin.

**Comment by FormidablePencil** [comment]
@krzkaczor I 
npx hardhat > "Create an advanced sample project that uses TypeScript" which installed typechain-hardhat and all the necessary dependencies for it to work with solidity.
Then I `npm install --save-dev @nomiclabs/hardhat-vyper` and put import "@nomiclabs/hardhat-vyper"; in hardhat.config.ts for vyper to work. Vyper and solidity contracts compile properly, using vyper contracts in tests work but the types for vyper fail to generate whereas solidity contracts don't.
Here's the repo with the same steps taken and with the artifacts committed https://github.com/FormidablePencil/types-for-vyper-fail/tree/master/typechain. You'll find that no types nor factories were generated. Maybe hardhat failing to generating *dbg.json in artifacts/contracts/ for vyper contracts has something to do with it but from what I read was that that file was for debugging purposes. Idk. I've been trying to get this to work with little to no luck.

**Comment by krzkaczor** [comment]
I think you're hitting this problem described in the [readme](https://github.com/dethcrypto/TypeChain/tree/master/packages/hardhat):

> Warning: before running it for the first time you need to do hardhat clean, otherwise TypeChain will think that there is no need to generate any typings. This is because this plugin will attempt to do incremental generation and generate typings only for changed contracts. You should also do hardhat clean if you change any TypeChain related config option.


Try `hardhat clean` and then `hardhat compile`.

**Comment by FormidablePencil** [comment]
Cleaned and compiled but type issue persisted for vyper.

**Comment by krzkaczor** [comment]
Quick workaround: use typechain cli directly.

 https://github.com/dethcrypto/TypeChain/issues/594

**Comment by FormidablePencil** [comment]
I managed to concoct this command `npx typechain --target=ethers-v5 './artifacts/contracts/**/+([a-zA-Z0-9_]).json' --out-dir "./typechain/"` which generates the types for all contracts written in Solidity and Vyper but despite the types having been generated they aren't being applied by hardhat. In hardhat.d.ts it looks like hardhat completely ignores those generated files and recompilation on file change doesn't help either. Manually updating this autogenerated file did the trick.

    getContractFactory(
      name: <name_of_contract>,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.<factory>>;

    getContractAt(
      name: <Name_of_contract>,
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.<ContractTypes>>;

**Comment by krzkaczor** [comment]
Yes. Hardhat.ts is a file generated by hardhat plugin. If you use CLI directly it won't be generated (updated). I would suggest using casts in your code or manually updating the file (or contributing with a fix to hardhat plugin! ;) )

**Comment by FormidablePencil** [comment]
Thanks for your help. I'll work with this solution and let the idea of contributing to hardhat with a fix marinade in my head.

**Comment by wottpal** [comment]
FYI this issue still persists and the above workaround still works.
