### ISSUE TITLE
Improving of the generated Web3 contracts

### ISSUE THREAD

**Issue by nivida** [ethereum-ts/TypeChain#147]
It's not required to wrap these methods. 

You could do something like this: 

``` javascript 
import {Contract} from 'web3-eth-contract';

class MyContract extends Contract {
// pre inject abi
}
```

**Comment by krzkaczor** [comment]
I think you're referring to `legacy` target (web3 0.20.x), right? It's done like this to add promises supports and (subjectively) improve the API. 

We don't do it anymore for any other targets. Reopen please if I am mistaken.
