### ISSUE TITLE
add ethereum json rpc specification support

### ISSUE THREAD

**Issue by shanejonas** [ethereum-ts/TypeChain#165]
**Abstract**
There exists a specification for Ethereum JSON-RPC that is expected to be implemented by all client developers. The OpenRPC document can be found [here](https://github.com/etclabscore/ethereum-json-rpc-specification/blob/master/openrpc.json).

Within the above linked repo you will also find generated code for different languages, like typescript, for making RPC calls to any Ethereum client.

**Describe the solution you'd like**
I'd like to see TypeChain add support for the [typescript client generated via this specification](https://github.com/etclabscore/ethereum-json-rpc-specification#javascripttypescript).

**Additional context**

- EIP 1901 -  https://eips.ethereum.org/EIPS/eip-1901
- https://github.com/etclabscore/ethereum-json-rpc-specification

**Comment by krzkaczor** [comment]
JSON-RPC schema is static, isn't it? TypeChain shines with dynamic schemas ie. created based on contract ABI. In this case JSON-RPC schema is all that it's needed to generated typed client and as you noted it already exists. 

So I am not sure what TypeChain can bring to the table? Did I misunderstand something?

**Comment by shanejonas** [comment]
The idea is to use the client generated from this https://github.com/etclabscore/ethereum-json-rpc-specification, in place of ethers.js or web3. and add it as a target for typechain.

we could have another layer on top of our own client generator to create contract classes for ABIs, but wanted to see if there was any interest in integration here first.

**Comment by krzkaczor** [comment]
Yeah, building directly on top seems like a good idea. 

If I were you I would just wait a little bit (1 month?). Huge refactoring is coming to TypeChain after which anyone (finally) will be able to create its own target. Just by creating a npm package. I think this is exatly what you are waiting for.

**Comment by shanejonas** [comment]
Great.

Any thoughts on multi-language?

Right now we have typescript/rust support, will have more in the future. Ideally we can do this same pattern for rust to interact with contracts.

**Comment by krzkaczor** [comment]
Hey! @shanejonas, with `TypeChain@1.0.0` you should be able to easily write your own target to generate code tailored for your needs. Generated code can be a different language than TypeScript.
