### ISSUE TITLE
Typings for web3@2.0.0-alpha.x

### ISSUE THREAD

**Issue by eswarasai** [ethereum-ts/TypeChain#170]
### Description
The latest version of TypeChain supports the target web3-1.0.0 to it's latest stable version of `^1.2.1` which is basically the `web3@1.0.0-beta.37`

Earlier there was an issue to support [`web3@^1.0.0-beta.38`](#135) which got released as [`typechain@0.3.12`](#141 ). Since it's now moved to `web3@2.0.0-alpha.x` where they ship their own typings instead of using the DefinitelyTyped package of `@types/web3`, I was wondering maybe if a new target for `web3@2.0.0` needs to be created to support the latest web3 version.

**Comment by krzkaczor** [comment]
I am planning huge refactoring very soon. Each target would become its own package (in this repo, monorepo style). I imagine `web3@2` being a separate, official target.

**Comment by eswarasai** [comment]
@krzkaczor - Thanks for the update. Let me know if you'd need any help with the refactoring. I'd be more than happy to help you out in any way I can. Thanks 🙂

**Comment by krzkaczor** [comment]
Thanks! I will create a detailed issue with my plans for the future and let you know :)

**Comment by krzkaczor** [comment]
@eswarasai TypeChain rewrite is essentially done. Now targets live in a separate packages (offical targets live in this repo). https://github.com/ethereum-ts/TypeChain/pull/172

Would you be interested in kicking off work regarding web3-2 target? I can request GitCoin bounty for this.

**Comment by eswarasai** [comment]
@krzkaczor - Wow, that's a huge PR. I'll spend sometime going through the package changes and yes, I'd love to take care of the `web3-2.0.0` target. Thanks for letting me know 🙂

**Comment by krzkaczor** [comment]
Great! I will add some quick migration guide to the readme for current users... 

btw. are u using currently web3 1.x.x target? Can I ask you to upgrade and let me know if you have encountered any issues?

**Comment by eswarasai** [comment]
Sure. I'll upgrade and see if I face any issues with `web3@1.0.0` target 👍

**Comment by krzkaczor** [comment]
Finally, `1.0.0` is merged and released! 🎉 Feel free to work on `web3-v2` target :)

**Comment by eswarasai** [comment]
@krzkaczor - Do we still support `web3@0.20.x`? The reason I'm asking this is because I still see the main `package.json` having this package as well as it's types. I'm having a difficulty in getting integration tests working for both `web3-v1` as well as `web3-v2` working locally at the moment.

**Comment by krzkaczor** [comment]
@eswarasai no - I decided to remove legacy target as I think `web3-v1` was around for a long time and it's good enough to migrate.

It is possible to migrate it but I thought that it's not that popular anymore.

This is core's package.json  https://github.com/ethereum-ts/TypeChain/blob/master/packages/core/package.json there is no sign of `web3@0.20` If you're looking at monorepo's package.json, it's there i think because some tests rely on it or some test time util.

**Comment by eswarasai** [comment]
Yeah, I was referring to the Monorepo's package.json which is only being utilised by the tests at the moment. Thanks for the above explanation, I think I know what I've missed. Let me give it a shot and get back again in case I have any queries.

BTW, is there any Slack/Discord channel where I can drop a PM? Thanks!

**Comment by krzkaczor** [comment]
Not yet, but it's a good idea to create one! We are already making some big steps towards making this org operating better. 

For now, feel free to dump your thoughts here, we won't annoy anyone since it's only 2 of us getting notifications here.
