### ISSUE TITLE
Ability to import event types

### ISSUE THREAD

**Issue by dchambers** [ethereum-ts/TypeChain#173]
Great tool, really really helpful 🙌 This is more of an info sharing issue than anything else, so feel free to close once you've seen it.

When using `web3`, I wanted a way to be able to use the same typed event handling function for both new events and for historical events. This means that event handling function can not be defined in-line, and therefore the function parameters need to be explicitly typed. Because these types aren't actually exported however, this is not easy to do.

To get at them, I've ended up with this `EventType` type:

```ts
export type EventType<E extends ContractEvent<any>> = Parameters<
  Extract<Parameters<E>[1], Function>
>[1]
```

which I use within my code like so:

```ts
type TransferEvent = EventType<Erc20Contract['events']['Transfer']>
```

I'm posting this issue as it may be helpful for other developers too. It may even make sense to make this, or something like it, directly available from the `types.d.ts` file.

**Comment by krzkaczor** [comment]
This is a valid point thanks! I am gonna close this for now and if more people find this useful we can make your `EventType` type part of generated code or some helper lib.

I think using something like `Erc20Contract['events']['Transfer']` is a way to go to get event type.

**Comment by AuHau** [comment]
Thanks for sharing!

I also think it would be beneficial to export each event as a separate interface that people could import and us.

**Comment by krzkaczor** [comment]
@AuHau I've added exactly this in https://github.com/ethereum-ts/TypeChain/pull/219 For now only for `web3v1` branch.

I am gonna reopen this issue until it's merged.

**Comment by krzkaczor** [comment]
https://github.com/ethereum-ts/TypeChain/releases/tag/v2.0.0

**Comment by dchambers** [comment]
Many thanks @krzkaczor, much appreciated 🙇

**Comment by AuHau** [comment]
Super-duper awesome! Thanks!
