### ISSUE TITLE
Ensure that class names are normalized before code generation

### ISSUE THREAD

**Issue by krzkaczor** [ethereum-ts/TypeChain#195]
Files named like `super-contract.abi.json` can generate classes with names like `super-contract.abi` which are producing syntax error.

We should normalize class names even if it makes in not unique (you can always rename on import).

**Comment by FSM1** [comment]
also ran into this error when attempting to use ABI's generated by `etherlime compile` with the `--exportAbi` flag.

**Comment by krzkaczor** [comment]
https://github.com/ethereum-ts/TypeChain/issues/204
