### ISSUE TITLE
Getting encoded data when using Typechain & Truffle target

### ISSUE THREAD

**Issue by alsco77** [ethereum-ts/TypeChain#208]
## Question

I notice in some old [blog posts ](https://blog.neufund.org/introducing-typechain-typescript-bindings-for-ethereum-smart-contracts-839fc2becf22) that it's possible to call `getData()` after a function call.

That method doesn't seem to be exposed any more -- I can't see where the call comes from. I have both the TS Artifact (xContract) and the Deployed version (xInstance), however can't find any funcs relating to getting raw txData.

Is this available somehow?

Edit: Used `contratnameInstance.contract.methods.methodName(param1, param2).encodeABI();`

**Comment by krzkaczor** [comment]
This blog post presented something that we called `legacy` target and it's not used anymore. 

You should simply use whatever method is right for your web3 access library. 

I see that you figured it out 👍
