### ISSUE TITLE
Support for function overloading

### ISSUE THREAD

**Issue by alsco77** [ethereum-ts/TypeChain#210]
## Target
Truffle

## What
It seems that the outputted contract typings do not support [overloading](https://solidity.readthedocs.io/en/v0.5.15/contracts.html#function-overloading). I have multiple 'doThis' functions accepting different arguments however only one is accessible in the TS Instance output

edit: Possibly relevant https://github.com/trufflesuite/truffle/issues/737

**Comment by krzkaczor** [comment]
@alsco77 yes, currently we don't support to function overloading. Releated to: https://github.com/ethereum-ts/TypeChain/issues/150
