### ISSUE TITLE
BN.js vs BigNumber.js in Truffle target

### ISSUE THREAD

**Issue by alsco77** [ethereum-ts/TypeChain#211]
## What

The typings in the output typings use BigNumber.js but an assertion in our test cases comparing the output against an equivalent bignumber.js is failing. Converting the test data to `BN.js` causes the test to pass. Not sure how it's slipping through, but maybe its worth being explicit in using BN.js. 

Based on this article, seems like Truffle migrated from `bignumber.js` to `BN.js` in v5 https://medium.com/coinmonks/upgrading-to-truffle-5-22aedc7c2a4d

Happy to help if you can point me in the right direction

**Comment by krzkaczor** [comment]
Any chance it's related to this: https://github.com/ethereum-ts/truffle-typings/issues/14

**Comment by alsco77** [comment]
Looks like it's been solved in this commit > https://github.com/ethereum-ts/TypeChain/pull/199/commits/a93ff6865c7ee69c028201485d724054cb6ba4cf in this PR > https://github.com/ethereum-ts/TypeChain/pull/199

Will try loading up @typechain/truffle-v5 as specified in the PR when I get a chance

**Comment by alsco77** [comment]
Confirm working with:
 - `@typechain/truffle-v5`
 - `typechain@1.0.4`

cmd: `typechain --target 'truffle-v5'`

Caveat: Only works with `1.0.4` When using typechain@1.0.3, 1.0.5 or beta, the target only searches packages prefixed with `typechain-target-` and not `@typechain/`.

**Comment by krzkaczor** [comment]
@alsco77 yeah I am aware of this regression, thanks for reporting.

**Comment by gorgos** [comment]
The solution from @alsco77 works, even though not ideal. I also had to exclude one contract that has a new 0.6 receive fallback function via `yarn typechain --target truffle-v5 './build/**/!(ContractName).json'`

**Comment by krzkaczor** [comment]
It should be fixed in ver 2.0. Please verify. Now we even have examples with truffle projects ;)

https://github.com/ethereum-ts/TypeChain/releases/tag/v2.0.0
