### ISSUE TITLE
Fails to generate types with a library that defines enums

### ISSUE THREAD

**Issue by stwiname** [ethereum-ts/TypeChain#216]
When I attempt to generate types I am getting this error `Error occured:  Unknown type: ALib.BOOL`

I have attached a minimal example: [Archive.zip](https://github.com/ethereum-ts/TypeChain/files/4212472/Archive.zip)
To repro: `yarn && yarn build`

The error seems to be the same as https://github.com/ethereum-ts/TypeChain/issues/125 but is still happening

**Comment by quezak** [comment]
Preliminary research shows that the ABI for the `other` function is different for a library:
```jsonc
// ...
      "inputs": [
        {
          "internalType": "enum ALib.BOOL",
          "name": "b",
          "type": "ALib.BOOL"
        }
```

While if I just change `interface ALib` to `contract ALib`, the type of the argument is plain `uint8`:
```jsonc
// ...
      "inputs": [
        {
          "internalType": "enum ALib.BOOL",
          "name": "b",
          "type": "uint8"
        }
```

I'll check if that's only when compiling with Truffle (personally I'm using Waffle :) )

**Comment by quezak** [comment]
Confirmed, the situation is the same. We'll need to see why does the ABI differ between these two cases and how can we handle that in the generation step -- it will probably affect all targets.

Btw, sorry @stwiname for the delayed response.

**Comment by SilentCicero** [comment]
I'm stuck on this as well.

**Comment by quezak** [comment]
@SilentCicero what solc version are you using? I'm wondering if it's still the same in v0.7.0

**Comment by SilentCicero** [comment]
6.8 currently with buidler

**Comment by krzkaczor** [comment]
@stwiname @SilentCicero Can someone prepare minimal repro for this?

**Comment by quezak** [comment]
@krzkaczor OP already contains a minimal repro :D when I checked it in March it was correct (ie. was bugged as described [above](https://github.com/ethereum-ts/TypeChain/issues/216#issuecomment-606583020))

**Comment by krzkaczor** [comment]
Sorry I missed it 😆 I will work on this later today

**Comment by krzkaczor** [comment]
This should be fixed now! Relased as `typechain@2.0.1`

**Comment by SilentCicero** [comment]
Sweet, thanks all!

**Comment by cameel** [comment]
This is not the only inconsistency in the library ABI. This comes mostly from the fact that selectors for library functions are computed differently than for contract functions, but still, it's a bit of a mess. There's already [an issue for it in Solidity repo](https://github.com/ethereum/solidity/issues/9278) and the discussion on how to handle it is ongoing. Since you're clearly affected by this, any feedback from your side would be appreciated.
