### ISSUE TITLE
Error occured:  Couldnt find truffle.

### ISSUE THREAD

**Issue by ghost** [ethereum-ts/TypeChain#217]
Following the setup guide in the TypeChain readme and I'm getting the following error:

```
Error occured:  Couldnt find truffle. Tried loading: typechain-target-truffle, E:\MAMP_V3\htdocs\solidity\demo\truffle.
Perhaps you forgot to install typechain-target-truffle?
```

I'm running VS Code on Windows 10.

`npm i -g typechain`
`npm i typechain-target-truffle`
`typechain --target=truffle // error`

Inside `E:\MAMP_V3\htdocs\solidity\demo\truffle` I have run `truffle init`.

**Comment by sriharikapu** [comment]
`typechain --target truffle-v5 \"build/contracts/**/*.json\"`

May be this might help

**Comment by quezak** [comment]
@sriharikapu is right -- we don't have a `truffle` target package anymore, but two separate targets `truffle-v4` and `truffle-v5`, [as shown in the README](https://github.com/ethereum-ts/TypeChain#cli).

I think the issue can be closed, feel free to comment if the issue is still present.
