### ISSUE TITLE
Typechain only generates d.ts files

### ISSUE THREAD

**Issue by matthieu-beteille** [ethereum-ts/TypeChain#220]
Hello,

I am trying to use typechain (target web3-v1) on a project, but all I get is a bunch of `d.ts` files with the types but no implementation:

for instance:

```Typescript
/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class AddressStorage extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): AddressStorage;
  methods: {
    getAddress(_key: string | number[]): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
```

I would expect to be able to use some code directly? Am I misunderstanding anything? Could you point me to an example?

**Comment by krzkaczor** [comment]
Hey!

> all I get is a bunch of d.ts files with the types but no implementation

This is how TypeChain works. You use your web3 library as you would but then cast  web3 untyped contract to a type generated by TypeChain. 

You will find many examples in our tests: https://github.com/ethereum-ts/TypeChain/blob/master/test/integration/targets/web3-v1/DumbContract.spec.web3.ts

Note: `deployContract` helper function.

Let me know if you have any other questions :)

**Comment by matthieu-beteille** [comment]
Makes a lot of sense now.

I think showing a quick snippet in the readme or pointing to the `deployContract` function would be very useful :)

Thanks for your quick response.
