### ISSUE TITLE
NatSpec parsing

### ISSUE THREAD

**Issue by chmanie** [ethereum-ts/TypeChain#221]
I would like to create a documentation from the TypeScript code I am generating. Is parsing and copying the [NatSpec](https://solidity.readthedocs.io/en/v0.5.8/natspec-format.html) comments from the abi (rather the AST) a desired functionality of this library? I would add a PR

**Comment by krzkaczor** [comment]
Hey @chmanie, thanks for this issue! I think copying NatSpec would be great for DX as IDEs could display a documentation from solidity code when interacting with the contract.

I can't find any information about NatSpec being part of the ABI. Can u share some examples? As far as I can tell, it seems like it's a separate file.

Another thing is that as we speak TypeChain goes through quite a big rewrite happening here: https://github.com/ethereum-ts/TypeChain/pull/219 So if supporting this would require broader changes I think it would make sense to merge #219 first. In a couple of days we should have a stable branch again.

**Comment by chmanie** [comment]
Hey @krzkaczor! NatSpec sadly isn't part of the ABI but it's still provided by the solidity compiler as part of the AST. So what you'd have to do is iterate the AST and find the `documentation` field for the function you're looking for. I think this would just require some changes for the targets, but I could create an external module to abstract this functionality (to be used in the targets, maybe optionally). Let me know if this is a valid path for you.

**Comment by chmanie** [comment]
Actually, you're right. This would require the `Contract` interface to expose the AST. Maybe that would be possible? I'm happy to help and implement that in v2

**Comment by chmanie** [comment]
I just looked into it again. To get the comments we'd need to also get the AST from the compiled json files here: https://github.com/JoinColony/TypeChain/blob/kk/new-architecture/packages/typechain/src/parser/abiParser.ts#L245

Something like
```
return {
  abi, // the actual `abi` object that we are returning right now
  ast // the ast to also be able to parse the NatSpec comments if they are available (truffle/solc usually generate them, afaik)
}; 
```

That would require the plugins to behave slightly different (get the abi from the object, instead of it just being an array). I could make these changes, just let me know if that's okay with you.

**Comment by krzkaczor** [comment]
Okay I see. I think this should be implemented in a way that it's not a breaking change. This could be merged into `FunctionDeclaration`/`EventDeclaration` as optional `natSpec?: string` field (or something similar). Then targets would generate appropriate tsdoc comment before item. What do you think?

Currently, CLI expects a glob pattern describing ABIs. We need to tweak docs later to show that this can be a bigger compilation artifact too.

Can paste here a sample compilation artifact with ABI and natspec so we are all on the same page? I think we already parse such files and we take only abi from them.

If you have time, please work on this. It would be a great addition to TypeChain!
I am not planning to change anything in `packages/typechain/` on this branch: https://github.com/ethereum-ts/TypeChain/pull/219 This branch is pretty stable now and actually I am changing a focus on writing docs/missing readmes now and preparing beta relase.

**Comment by chmanie** [comment]
Hm. I don't think this could be implemented without a breaking change in `typechain` as the parser only returns the abi and not the ast. Our generated json files look like this:

```js
{
  "contractName": "TheContractName",
  "abi": [
    // This is what you're currently extracting from the contracts
  ],
  "metadata": "a whole bunch of metadata",
   // Some more fields here ...
  "sourcePath": '"some/path",
  "ast": {
    // This is where we could extract the documentation!
    "nodes": [
      // NatSpec comments generate a `documentation` field, right next to the method/contract node
    ]
  }
}
```

I hope this explains where I'm coming from. I'd love to work on this; hope we can find a way forward!

**Comment by krzkaczor** [comment]
>  I don't think this could be implemented without a breaking change in typechain as the parser only returns the abi and not the ast

Gosh, nvm you're right 🤦 I didn't touch that part of the code in a while and I thought that we have a single function to extract and parse contract ABI and `extractAbi` is just a private interface but this is not true and targets call both actually.

> as the parser only returns the abi and not the ast. 

Yes, something like `return {abi,ast}; ` makes sense, then this could be fed to the parser and we would get parsed declarations enriched with natspec. Just note that `ast` should be always optional as it can be missing.

**Comment by chmanie** [comment]
Wonderful, it seems we have a way forward :) I'll start working on this today!

> Just note that ast should be always optional as it can be missing.

Roger that!

**Comment by chmanie** [comment]
I started here: https://github.com/ethereum-ts/TypeChain/pull/222

Let me know if that goes into the totally wrong direction

**Comment by krzkaczor** [comment]
Thanks for you help!
https://github.com/ethereum-ts/TypeChain/releases/tag/v2.0.0

**Comment by chmanie** [comment]
Wohooo, congrats on the v2.0.0!
