### ISSUE TITLE
Recompile only changed files?

### ISSUE THREAD

**Issue by kermankohli** [ethereum-ts/TypeChain#223]
Hey, a feature that would be *amazing* if only the files that have changed are compiled (and watches for them). How difficult would this be to do? Would be happy providing a bounty for this.

**Comment by krzkaczor** [comment]
Hey!

Can you elaborate on why this is needed? Do you use TC for smart-contract development where ABIs change often? I was always under the impression that TC is reasonable fast. 

Few thoughts
1. Have you thought about using something like `lint-staged`?
2. Checking file status can be actually done very efficiently just based on timestamps ie. find inputs that are newer than outputs and recompile only those. I believe `tsc` uses the same trick. I believe this would be an easy way to implement such feature.
3. We can actually put more effort into speed optimizations. An easy path forward is parallel execution. 

Cheers!

**Comment by kermankohli** [comment]
Yeah so basically I write stubs for my contract, generating typings and then write unit tests. After writing in my tests I write the actual code then need to compile contracts and typings so the tests can execute. Currently this workflow is super slow and annoying to deal with. If contracts can recompile and typechain rebuilds what was changed that'd be 10x faster.

**Comment by PierrickGT** [comment]
> Yeah so basically I write stubs for my contract, generating typings and then write unit tests. After writing in my tests I write the actual code then need to compile contracts and typings so the tests can execute. Currently this workflow is super slow and annoying to deal with. If contracts can recompile and typechain rebuilds what was changed that'd be 10x faster.

I have the exact same problem, it's slowing things down a lot to have to regenerate types each time that I run tests.
Has there been any improvements on this side? It looks like it could be pretty useful to have a command to at least disable types generation when we run tests.

**Comment by krzkaczor** [comment]
@PierrickGT it is supported if you use harhat (via harhdat target). What's your setup @PierrickGT?

**Comment by PierrickGT** [comment]
> @PierrickGT it is supported if you use harhat (via harhdat target). What's your setup?

I do use it via Hardhat but I suppose my setup needs some improvement.
Here is a project in which I use Typechain and Hardhat: https://github.com/pooltogether/aave-yield-source

**Comment by krzkaczor** [comment]
Closing this as this is implemented
