### ISSUE TITLE
Fails to generate typings for events with no parameter names`

### ISSUE THREAD

**Issue by kermankohli** [ethereum-ts/TypeChain#224]
Typchains fails to generate typings for an event like this:

`event PairCreated(address indexed token0, address indexed token1, address pair, uint);`

```SyntaxError: Parameter declaration expected. (111:73)
  109 |     filters: {
  110 |       
> 111 |   PairCreated(token0: string | null, token1: string | null, pair: null, : null, ): EventFilter;
      |                                                                         ^
  112 | 
  113 |     };```

**Comment by krzkaczor** [comment]
This is fixed in: https://github.com/ethereum-ts/TypeChain/pull/219

I would appreciate testing our beta release: 

```
typechain@2.0.0-beta2
target-name@1.0.0-beta1
```

NOTE: that we changed naming schema for targets: 
https://github.com/ethereum-ts/TypeChain/pull/219

**Comment by krzkaczor** [comment]
https://github.com/ethereum-ts/TypeChain/releases/tag/v2.0.0
