### ISSUE TITLE
Typechain changing file names

### ISSUE THREAD

**Issue by PhABC** [ethereum-ts/TypeChain#234]
I just upgraded from `typechain@1.03` to `typechain@2.0.0` and the generated file had a different name, which is unfortunate as I would have to modify many files to adapt to that change. Here are some examples of files that were affected:

`contracts/IERC20.d.ts` is now `contracts/Ierc20.d.ts`
`contracts/ERC1155.d.ts` is now `contracts/Erc1155.d.ts`

Any config I can setup such that the name of these type files is the same as the abi's name? Would be simpler.

**Comment by petejkim** [comment]
I've run into something similar.

I had a name like `FooV1_1` where `V1_1` signifies `v1.0`, but TypeChain changes the name to `FooV11` (v11) :(

Could you make it preserve original naming please?

**Comment by krzkaczor** [comment]
Hey @PhABC 

Yeah, it's one of the breaking changes in v2. Now we try to normalize naming to avoid running into problems with invalid names (symbols) for TypeScript types. 

What's not necessary correct is that perhaps we should preserve original filenames for files and just normalize names for types.

**Comment by jchittoda** [comment]
I am also getting the same issue after upgraded to `typechain@2.0.0`. 

I had to upgrade to `typechain@2.0.0`, because the older version generates typing files with `BigNumber`. In our test cases we want to use `BN`. Hence, we had to upgrade it to `typechain@2.0.0`, which uses `BN`.

Can you suggest a better solution? So that we can use `BN` in generated typing files without upgrading to `typechain@2.0.0`

**Comment by RobertoSnap** [comment]
Hi

Also running into this issue now.

**Comment by PhABC** [comment]
Bump

This adds significant additional work since the names are different from the artifacts the typings are generated from.

**Comment by PhABC** [comment]
Made a PR for it ; https://github.com/ethereum-ts/TypeChain/pull/290

**Comment by quezak** [comment]
@krzkaczor what were the file/contract names resulting in invalid typescript symbols back when you originally changed this?

**Comment by krzkaczor** [comment]
@quezak @PhABC there is a bunch of tests:
https://github.com/ethereum-ts/TypeChain/blob/master/packages/typechain/test/parser/normalizeName.test.ts

It looks like what @PhABC needs makes sense and was omitted by mistake. 

I will merge your (@PhABC) PR and add tests in a sec.

**Comment by krzkaczor** [comment]
Take a look guys for the new tests and impl: https://github.com/ethereum-ts/TypeChain/pull/293/files

**Comment by krzkaczor** [comment]
Released as `typechain@4`
