### ISSUE TITLE
Suggestion: add deprecation warnings for old npm packages

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum-ts/TypeChain#236]
I recently started using the typechain@2.0.0 and typechain-target-ethers@1.0.4 packages, but it took me a while to realise that the relative versions are incompatible. It seems that the latter is now [@typechain/ethers-v4](https://www.npmjs.com/package/@typechain/ethers-v4).

It'd be good to let users know about this change. There are many tutorials on the Internet that still reference the old "typechain-target-name" packages.

**Comment by krzkaczor** [comment]
Yes, definitely good idea. I am gonna try to do it in a sec.

**Comment by krzkaczor** [comment]
DONE. Thanks for bringing up this issue to my attention!

**Comment by PaulRBerg** [comment]
Amazing, thanks for the quick turnaround!
