### ISSUE TITLE
Artifacts type missing from generated typings

### ISSUE THREAD

**Issue by DanTup** [ethereum-ts/TypeChain#241]
I ran `typechain --target=truffle-v5 --glob "build/contracts/*.json"` and it generated all my typings:

```
ts-gen: Running TypeChain
ts-gen: build/contracts/*.json matched 2 files.
ts-gen: Processing build\contracts\Migrations.json
ts-gen: Writing file: types\truffle-contracts\Migrations.d.ts
ts-gen: Processing build\contracts\XXX.json
ts-gen: Writing file: types\truffle-contracts\XXX.d.ts
ts-gen: Writing file: types\truffle-contracts\index.d.ts
ts-gen: Writing file: types\truffle-contracts\types.d.ts
ts-gen: � All done! Generated files: 4
```

However in the generated `types.d.ts` it has this:

```ts
declare const artifacts: Truffle.Artifacts;
```

But there's a red squiggle under `Artifacts` as it doesn't seem to exist in the generated `Truffle` namespaces (it has many other definitions, like `Accounts`, `TransactionDetails`, `TransactionLog`).

Is this a bug, or is there something else I need to do? I thought maybe I need `truffle-typings`, however the readme says that's deprecated and everything is generated here.

Thanks!

**Comment by DanTup** [comment]
Ok, I just found them defined in `index.d.ts` like this:

```ts
declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Migrations"): MigrationsContract;
      require(name: "xxx"): XXXContract;
    }
  }
}
```

I guess this makes sense - now the `require` call should only accept the names defined. However, I'm not sure why TypeScript isn't picking them up and is giving errors (and the result, is that my `artifacts` in the test file is `any` and I don't get any typing for my contract).

**Comment by DanTup** [comment]
Solved it by creating an empty `tsconfig.json`! I'm not sure I entirely understand why, but probably it has something to do with TS not knowing where the root of the proejct is (so maybe it doesn't read `./typings` and just treats each file loose?).

(Sorry for the spam!)

**Comment by krzkaczor** [comment]
Haha no problem. It's nice that you posted it right before I went to sleep, I woke up 8h later and it's already solved 😆 

When in doubt take a look at our examples: https://github.com/ethereum-ts/TypeChain/tree/master/examples/truffle-v5

**Comment by DanTup** [comment]
Yeah, I was using that as a reference - but started from an empty project to make sure I understood everything I was adding. I'd been bitten by weird behaviour with no `tsconfig.json` in the past, so not sure why it hadn't occurred to me earlier!

FWIW, on Windows, I found that using single quotes around the glob here didn't work:

https://github.com/ethereum-ts/TypeChain/blob/849a90f81b0753def86c989e139138ea38f4721f/examples/truffle-v5/package.json#L8

If I ran the same command directly from a shell it was fine, but when running with `npm run generate-types` it would always say the glob matched nothing. Swapping the quotes to `\"` solved the issue. I'm not sure I understand that either, but if you can repro, it may be worth updating there for those using it as a reference on Windows :-)

Thanks!

**Comment by krzkaczor** [comment]
Thanks for this @DanTup, I will change them to double-quotes.

**Comment by DanTup** [comment]
I couldn't find a good explanation of this online (lots of examples use single quotes), but for reference, here's the output I had for each:

### Fails with single quotes in npm script

```
PS M:\Dev\MyProject> npm run generate-types

> @ generate-types M:\Dev\MyProject
> typechain --target=truffle-v5 --glob 'build/contracts/*.json'

ts-gen: Running TypeChain
ts-gen: 'build/contracts/*.json' matched 0 files.
ts-gen: Writing file: types\truffle-contracts\index.d.ts
ts-gen: Writing file: types\truffle-contracts\types.d.ts
ts-gen: � All done! Generated files: 2
PS M:\Dev\MyProject>
```

### Works with double quotes in npm script

```
PS M:\Dev\MyProject> npm run generate-types

> @ generate-types M:\Dev\MyProject
> typechain --target=truffle-v5 --glob "build/contracts/*.json"

ts-gen: Running TypeChain
ts-gen: build/contracts/*.json matched 2 files.
ts-gen: Processing build\contracts\Migrations.json
ts-gen: Writing file: types\truffle-contracts\Migrations.d.ts
ts-gen: Processing build\contracts\Thing.json
ts-gen: Writing file: types\truffle-contracts\Thing.d.ts
ts-gen: Writing file: types\truffle-contracts\index.d.ts
ts-gen: Writing file: types\truffle-contracts\types.d.ts
ts-gen: � All done! Generated files: 4
```

### Works with single quotes from PowerShell terminal

```
PS M:\Dev\MyProject> node_modules\.bin\typechain --target=truffle-v5 --glob 'build/contracts/*.json'
ts-gen: Running TypeChain
ts-gen: build/contracts/*.json matched 2 files.
ts-gen: Processing build\contracts\Migrations.json
ts-gen: Writing file: types\truffle-contracts\Migrations.d.ts
ts-gen: Processing build\contracts\Thing.json
ts-gen: Writing file: types\truffle-contracts\Thing.d.ts
ts-gen: Writing file: types\truffle-contracts\index.d.ts
ts-gen: Writing file: types\truffle-contracts\types.d.ts
ts-gen: � All done! Generated files: 4
```

I don't know whether it's Windows specific, but I figured that might be something that might affect shell expansion.

By the way - slightly offtopic - do you have any examples using Chai with promises (https://www.chaijs.com/plugins/chai-as-promised/)? I couldn't figure out how to make this work, and using try/catch to check rejections is a bit cumbersome. Thanks!

**Comment by krzkaczor** [comment]
Thanks for this that's helpful, I think this could be impacted by different shell expansion mechanisms on different OSes... I have somewhere windows machine - I am gonna test it.

> By the way - slightly offtopic - do you have any examples using Chai with promises (chaijs.com/plugins/chai-as-promised)? I couldn't figure out how to make this work, and using try/catch to check rejections is a bit cumbersome. Thanks!

Not that I can think of... BUT! you should keep your eyes peeled for [earl](https://github.com/krzkaczor/earl), it's will support promises very soon ;) 

Btw. here's a chai's setup script for [TypeChain](https://github.com/ethereum-ts/TypeChain/blob/master/packages/target-web3-v1-test/test/setup.test.ts)

**Comment by DanTup** [comment]
> keep your eyes peeled for earl, it's will support promises very soon ;)

I'll keep my eyes open (I presume there will be a way to have it pulled into the generated files instead of Chai?), though that doesn't help today :-)


> Btw. here's a chai's setup script for TypeChain

I tried copying that setup, but it fails with:

> Cannot use import statement outside a module

So I tried with:

```ts
require("chai")
	.use(require("chai-as-promised"));
```

And this didn't fail, however a test like:

```ts
new Promise((resolve) => setTimeout(resolve, 100)).should.eventually.be.rejected
```

Fails with:

> Cannot read property 'eventually' of undefined

I've tried all sorts of combinations, but not managed to make anything work. If you know of anywhere that might have tests that have async asserts (or if there's a way for me to have typechain include a different assert lib that might), let me know :-)

**Comment by krzkaczor** [comment]
Just to clarify - TypeChain doesn't force you to use any particular assertion library. It just generates types for contracts. Truffle comes with chai and that's why you probably use `chai`. You won't find a sign of `chai / mocha` in generated typings.

As for you installation problems I am not sure really whats happening. If you submit a repo with reproduction I might be able to take a look.

**Comment by DanTup** [comment]
> Just to clarify - TypeChain doesn't force you to use any particular assertion library. It just generates types for contracts. Truffle comes with chai and that's why you probably use chai. You won't find a sign of chai / mocha in generated typings.

Ah - I have a file at `./types/truffle-contracts/types.d.ts` which I thought was being generated here, but I guess this is actually coming from the `truffle-typings` package.

I think this may be related to the runtime issue I'm seeing:

https://github.com/TypeStrong/ts-node#help-my-types-are-missing

Using the instructions there I can get the TypeChain typings to load to load (since they're in an `index.d.ts`) but not those from the `types.d.ts` file (which means `artifacts` isn't available).

I'm not tied to Truffle - I picked it only because it came up a lot in searching. I see you support some others (`ethers`, `web3`?). Do you have any opinions on them? Are any of them simpler to set up? Mainly I just want to be able to edit my contract in VS Code and write/run some basic tests (with some editor support, like TypeScript).

**Comment by DanTup** [comment]
I made a stripped down repo here if you'd like to take a look:

https://github.com/DanTup/truffle-test

Just run `npm install && npm test` and it'll fail with TS errors compiling because `expect` is missing. I don't think it's TypeChain's fault, but any insight you have would be appreciated! Thanks! 🙂

**Comment by mrwcjoughin** [comment]
@DanTup you just need to add this `import` statement at the top of every file you use `expect` in:
`import { expect } from 'chai'`

**Comment by DanTup** [comment]
But `expect` is already defined globally in `types/truffle-contracts/types.d.ts` and should be read from there? Importing `expect` still leaves the same issue for `contract` and `artifacts`.

I think the solution involves having `node-ts` read the `truffle-contracts/types.d.ts` file instead?

**Comment by DanTup** [comment]
BTW:

> You won't find a sign of chai / mocha in generated typings.

These are coming from the `types.d.ts` file written by the target-truffle-v5 package:

https://github.com/ethereum-ts/TypeChain/blob/f63bbe3504bb82eec2d683850998d8547b05f825/packages/target-truffle-v5/static/types.d.ts#L4-L11

https://github.com/ethereum-ts/TypeChain/blob/f63bbe3504bb82eec2d683850998d8547b05f825/packages/target-truffle-v5/src/index.ts#L49-L60

This results in `expect` being a `chai` interface automatically in all test files.
