### ISSUE TITLE
Unable to access types for events

### ISSUE THREAD

**Issue by DanTup** [ethereum-ts/TypeChain#242]
This isn't really a bug, more of a cry for help (or requires for a sample test)! I'm trying to write a test for events being emitted. I have something like this:

```ts
const foo = await MyContract.new();
const resp = await foo.bar("Test", { value: "3000000" });

expect(resp.logs.length).equals(1);
const evt = resp.logs[0];
expect(evt.event).equals("DidBar");
if (evt.event === "DidBar") {
  expect(evt.args.title).equals("Test");
}
```

I call  the `bar` function, then examine the `logs` to look for the `DidBar` event, and check its `title` property. However, this doesn't work because `evt.args.title` is not valid, because the type of `evt.args` is a union of all event types and they don't all have `title` fields (I expected that `if (evt.event === "DidBar")` would narrow the type, but that didn't seem to happen).

So my next attempt was to cast:

```ts
const evt = resp.logs[0] as Truffle.TransactionLog<DidBar>;
```

However `DidBar` is not in scope here, so I had to add:

```
import { DidBar } from "../types/truffle-contracts/MyContract";
```

However this fails when running `truffle test` with:

> SyntaxError: Cannot use import statement outside a module

I've been trying for a few hours to make this work (including different ways of importing, different tsconfig settings, etc.) with no joy.

An example of how to test an event (in a strongly typed way, without just casting to `any`) would be great :-) I did find some in some PRs merged here that looked related (for ex. https://github.com/ethereum-ts/TypeChain/pull/43) but they don't seem to be in `master` anymore, so I presume things have changed.

Thanks!

**Comment by DanTup** [comment]
I figured I could go with `as any` in the meantime:

```ts
expect(resp.logs[0].event).equals("DidBar");
const args = resp.logs[0].args as any;
expect(args.title).equals("Test");
```

But this fails at runtime with:

```
const args = resp.logs[0].args as any;
                               ^^

SyntaxError: Unexpected identifier
```

I can't figure out what's going on here. I thought maybe it was compiling the TS to a bad version of JS, but I tried several `target`s in `tsconfig.json` with no difference.

**Comment by krzkaczor** [comment]
It seems like you execute code as javascript not typescript. Again, take a look at truffle examples. Also here is, **slightly out of date**, step by step guide: https://github.com/ethereum-ts/truffle-typechain-example Probably you forgot to require `ts-node`.

**Comment by DanTup** [comment]
Ah, looks like that's part of the problem. I'm surprised the code ran at all until now. However, with that included and the full tsconfig.json copied from that repo, I see errors like:

```
error TS2304: Cannot find name 'artifacts'.
```

There are no issues in the IDE (it correctly shows what `artifacts` is and I can Go-to-Definition on it), and no errors when I run `tsc -p .` in the folder. Only happens when running `truffle test`.

I tried to clone that example you linked, but on Windows it fails to restore npm packages, wanting Visual Studio (it's trying to run node-gyp) w/ C++ build tools, so I can't really use that as an reference (I have copied its config and other files, but no change).

If you know of any up-to-date examples using this, let me know. I might have a go at writing the tests in Solidity to see if that works out any less complex. Everything I do with node/js/ts seems to turn out a lot more complicated than I was expecting! ;(

**Comment by DanTup** [comment]
Ok, I ditched truffle and switched to using web3 and geth locally, and I managed to get access to my events in tests :-)

https://github.com/DanTup/truffle-test/blob/ed632cf030311362bc12ca8328837f364d694cce/test/danny_contract.test.ts

The only weird thing is this:

```ts
const d = c as any as ContractsDannyContractSolDannyContract;
```

I can't find a way to make TypeScript happy about casting the contract to the generated type without going via `any`. I checked the examples, and it looks like the same is done there:

https://github.com/ethereum-ts/TypeChain/blob/849a90f81b0753def86c989e139138ea38f4721f/examples/web3-v1/src/index.ts#L13

**Comment by krzkaczor** [comment]
Yeah, it's expected. We just plug generated types on top, nothing better can be done at this point.

I am glad that you figured it out, I am gonna close this for now.
