### ISSUE TITLE
Cannot find name 'artifacts', 'contract' after upgrading to typechain v2 [truffle v5]

### ISSUE THREAD

**Issue by obernardovieira** [ethereum-ts/TypeChain#243]
Hey,
First and foremost, thank you so much for everyone's work here. It's great and extremely helpful.

I've built a [dapp boilerplate](https://github.com/HQ20/create-hq20-dapp) and I've been upgrading it recently to have something a bit different. Throughout that, I've upgraded [typechain to v2](https://github.com/HQ20/create-hq20-dapp/pull/540), and all the other dependencies attached to it. But because of that, I now [get some errors](https://travis-ci.org/github/HQ20/create-hq20-dapp/jobs/691313305) as described below.

Could you guys help me, please? I'll be very thankful.

```bash
Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

TSError: ⨯ Unable to compile TypeScript:
test/SimpleStorage.test.ts:4:23 - error TS2304: Cannot find name 'artifacts'.

4 const SimpleStorage = artifacts.require('SimpleStorage');
                        ~~~~~~~~~
test/SimpleStorage.test.ts:8:1 - error TS2304: Cannot find name 'contract'.

8 contract('SimpleStorage', (accounts) => {
  ~~~~~~~~
test/SimpleStorage.test.ts:8:28 - error TS7006: Parameter 'accounts' implicitly has an 'any' type.

8 contract('SimpleStorage', (accounts) => {
                             ~~~~~~~~

```

**Comment by krzkaczor** [comment]
This is truffle project right? Can u refer to our truffle example? (we have both for v4 and v5) https://github.com/ethereum-ts/TypeChain/tree/master/examples/truffle-v4

**Comment by obernardovieira** [comment]
ahh yes, sorry.
yeah, truffle project, v5.

**Comment by krzkaczor** [comment]
@obernardovieira so, did you figure it out? Please reopen if not. 

Sidenote: I feel like we should have step by step guides in example's readme...

**Comment by obernardovieira** [comment]
No, I was waiting for your answer, maybe you had a hint.
(I can't reopen, can you do it, please?)

Regarding the sidenote, yeah, I agree. I'd be up to help on that :+1: I like writing tutorials and examples.

**Comment by krzkaczor** [comment]
Based on the error messages it looks like tsc didn't pick up generated typings. Can u show us your `tsconfig.json` file? Do you use `types` or `typeRoot` field?

Also I just updated the examples, check them out they work like a charm now. 

> Regarding the sidenote, yeah, I agree. I'd be up to help on that 👍 I like writing tutorials and examples.


That would be great! We had step by step guide in the previous repo but now I think it's slightly outdated: https://github.com/ethereum-ts/truffle-typechain-example#setup but for sure it's a good start!

**Comment by obernardovieira** [comment]
>  Do you use types or typeRoot field?

I do, https://github.com/HQ20/create-hq20-dapp/blob/upgrade-typechain/templates/smart-contracts/tsconfig.json#L17 but if I use the tsconfig.json from the examples, I get exactly the same errors.

I downloaded the examples, and they work, but then start importing our files and the errors start to show up.

1.
```bash
import { should } from 'chai';                                                                                                                                                                    
       ^                                                                                                                                                                                       
SyntaxError: Unexpected token {
```

So I changed `import { should } from 'chai';` to `const chai = require('chai');`
2.
`Error: Cannot find module 'chai'`
And I see `Cannot redeclare block-scoped variable 'chai'.ts(2451)` in vscode. So I added an `export {}` and then got

```bash
export {}
^^^^^^
SyntaxError: Unexpected token export
```

So I eventually decided to rename `const chai = require('chai');` to `const chaiTest = require('chai');` and it worked.

Bu unhappy with the result I've decided to give a try with our [truffle-config.js](https://github.com/HQ20/create-hq20-dapp/blob/upgrade-typechain/templates/smart-contracts/truffle-config.js) but it didn't work. And then I've realized that all the errors are related to ts-node dependency.

Do you have any idea about that? Any alternative? I would like to use the `import` style, rather than `require`. I believe lots of other TS functionalities will be lost.

**Comment by krzkaczor** [comment]
Can u create a repository with reproduction? @obernardovieira

**Comment by obernardovieira** [comment]
Of course,

https://github.com/obernardovieira/experiment-typechain-truffle-v5

**Comment by junderw** [comment]
Having the exact same issue...

I had a similar issue with another project using jest, and the solution was something along the lines of adding the global libraries in the jest config file.

The funny thing in my situation is that the linters in my IDE are perfectly happy... They get all the types fine, autocomplete and everything.

But when I run truffle test all of the assumed global variables dealing with truffle / the generated types are forgotten apparently.

**Comment by alexmedkex** [comment]
The way I fixed this was to use the tsconfig.json file here 

https://github.com/ethereum-ts/truffle-typechain-example/blob/master/tsconfig.json

And then I changed `truffle-contracts` to `truffle-typings`, under `types`.

You will need the `truffle-typings` package installed in your project.

**Comment by gorgos** [comment]
I tried the solution by @alexmedkex and it worked. Then I tried to revert it, uninstalled `truffle-typings` again as this package is now deprecated. But it just continued working... 🤔 

So I can't test it right now, but maybe

```
"typeRoots": [
      "./node_modules/@types",
      "./node_modules/@typechain/truffle-v5/static/types.d.ts",
      "./types"
    ]
```

like this should fix it?

**Comment by naddison36** [comment]
For anyone else with this problem, I solved it by including Typechain's output folder in the Typescript config file `tsconfig.json`. By default, that's the `typechain` folder. It can also be set with Typechain's `--outDir` option.

```json
"include": [
    "./test",
    "./typechain"
  ],
```

I have a HardHat project using Truffle tests, so my full `tsconfig.json` file is 
```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true,
    "outDir": "dist"
  },
  "include": [
    "./test",
    "./typechain"
  ],
  "files": ["./hardhat.config.ts"]
}
```

FYI, my HardHat config in `hardhat.config.ts` is
```ts
import "@nomiclabs/hardhat-truffle5"
import "hardhat-typechain"

export default {
  solidity: "0.7.6",
  typechain: {
    target: "truffle-v5",
  },
};
```

**Comment by lebed2045** [comment]
does anyone have working example of truffle-5 + typescript? tests + migrator would be great!

**Comment by lebed2045** [comment]
I'm having the exactly same issues following the https://soliditydeveloper.com/typescript tutorial

**Comment by viraj124** [comment]
@naddison36 do you have the link of the repo where you had both hardhat and truffle running together i am actually facing the same issue

**Comment by cyrus1996** [comment]
Guy I have a working solution here : 

The compiler is not working probably because you haven't compiled your contracts yet, just run a 
```
npx truffle compile
npx typechain --target=truffle-v5 'build/contracts/*.json'
```

this will output a ./types directory with all your needed types, make sur to tell the TS compiler to read this file and this should do the job :)
