### ISSUE TITLE
Generated types can't be imported in a TypeScript npm package and built with rollup when using tsdx

### ISSUE THREAD

**Issue by pcowgill** [ethereum-ts/TypeChain#247]
### Goal

The goal is to be able to expose typings for specific smart contracts as an npm package that can be used to interact with those contracts. This way the user gets typings without needing to be able to run TypeChain on the contracts within their own project.

### Current Behavior

[TSDX](https://github.com/jaredpalmer/tsdx) (probably Rollup behind the scenes) struggles with building a `src/index.ts` file that imports generated TypeChain types. Here's a repo with a reproduction: https://github.com/pcowgill/tsdx-typechain/

### Expected behavior

`tsdx build` completes and uses the `.d.ts` type files generated by Typechain with `@target/ethers-v4` I'm importing in `src/index.ts`.

### Suggested solution(s)

I'm not sure if I need a rollup plugin, a different set of choices in `tsconfig.json`, or if something could be changed on TypeChain's end. Maybe TypeChain can change the output style of the `.d.ts` files so that it's easier to import and build with rollup via tsdx?

### Additional context

The type I'm trying to import is here https://github.com/pcowgill/tsdx-typechain/blob/primary/typechain/Greeter.d.ts

I committed the generated typings to the repo to make it easier to understand the reproduction without running it locally, but I know in most cases it would make more sense not to commit the generated files.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | 0.13.2 |
| TypeScript       | 3.9.5 |
| npm/Yarn         | npm 6.14.4 |
| Node             |  12.18.0 |
| Operating System | macOS 10.15.5 |
| TypeChain | 2.0.0 |
| ethers.js | 4.0.47 |
| @typechain/ethers-v4 | 1.0.0 |

Thanks!!

**Comment by krzkaczor** [comment]
Can u try using type only imports?

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html

**Comment by pcowgill** [comment]
@krzkaczor That appears to have worked! Great suggestion, thanks!
