### ISSUE TITLE
Adding ethers v5 target to TypeChain

### ISSUE THREAD

**Issue by zemse** [ethereum-ts/TypeChain#248]
I needed `ethers v5` typings in my project, I'm glad I found TypeChain which made work easy but it did not have ethers v5 target, so I forked the project and modified existing v4 for generating typings for ethers v5. https://github.com/zemse/TypeChain/tree/master/packages/target-ethers-v5. The commits aren't that organized because I was in a hurry, that's why I did not create a PR.

Would you guys welcome a PR if I rework on this to make it reviewable? I'm asking this in case someone is already working on creating a v5 target, then it would make sense for me to not do the rework.

Also, if I have any questions where/whom can I ask? (To clarify I mean if there is a gitter channel or something for quick communication else I would ask here)

**Comment by Jannis** [comment]
Yes please! 👍 (I'm not working on TypeChain but I'd love to see support for ethers v5 added).

**Comment by krzkaczor** [comment]
@zemse yes of course! Ethers-v5 target would be super useful. There is no one working on it afaik.

**Comment by krzkaczor** [comment]
Releated: https://github.com/ethereum-ts/TypeChain/issues/205

I will close this issue if you don't mind, and lets continue discussions on the other one.
