### ISSUE TITLE
Output NatSpec Comments

### ISSUE THREAD

**Issue by gregdhill** [ethereum-ts/TypeChain#267]
Package: `ethers-v4`

If the generated type declarations were to contain the respective NatSpec comments it would simplify doc generation using more standard tooling such as [TypeDoc](https://typedoc.org/). The added benefit with this is that it could also extract relevant documentation from wrapper libraries as opposed to native tooling (like [solidity-docgen](https://github.com/OpenZeppelin/solidity-docgen)) which is only able to parse Solidity.

**Comment by krzkaczor** [comment]
TypeChain already supports NatSpec.

[Readme note](https://github.com/ethereum-ts/TypeChain#natspec-support)
[Original issue](https://github.com/ethereum-ts/TypeChain#natspec-support)

You just need to provide a compilation artifact with NatSpec comments (not just raw abi).
Reopen please if you have more questions.
