### ISSUE TITLE
Typechain glob not matching to files on windows

### ISSUE THREAD

**Issue by zemse** [ethereum-ts/TypeChain#271]
The [repo](https://github.com/KMPARDS/esn-contracts) contains the following [script](https://github.com/KMPARDS/contract-template/blob/master/package.json#L10) for typechain.

```js
"typechain": "typechain --target ethers-v5 --outDir build/typechain 'build/artifacts/**/*.json'"
```

This generates typechain outputs on `macos`, `linux` but on `windows` the glob matches to 0 files and hence doesn't generate any typings file.

I've created a github workflow seperate jobs for `macos-latest`, `ubuntu-latest` and `windows-latest`. There the tests pass for macos, ubuntu while fail for windows giving typescript error (which is that it didn't find a typing file).

Run link: https://github.com/KMPARDS/contract-template/runs/967467001

Screenshots:

![Screenshot 2020-08-10 at 9 37 20 PM](https://user-images.githubusercontent.com/22412996/89804752-36b73900-db52-11ea-8588-c2fd332f1204.png)

**Comment by snaketh4x0r** [comment]
I m facing the same issue
I m using this
```typechain --target truffle './build/**/*.json'```
although currently I have booted a linux distro but I hope this gets fixed.
Typings files are generated but they don't have any contract interfaces generated correctly

**Comment by meryuhi** [comment]
I found a workaround is to remove the single quotes of the glob matching path, just use like
```
typechain --target truffle-v5 build/contracts/**/*.json
```

**Comment by rafinskipg** [comment]
Use this for both linux and windows support `\"`

```
typechain --target truffle-v5 \"build/contracts/**/*.json\"

```

**Comment by krzkaczor** [comment]
This doesn't seem to a TypeChain bug but rather a Windows oddity. 

Closing for now. If someone has an idea how we can improve this on our side LMK.
