### ISSUE TITLE
Optional arg name prefix / postfix 

### ISSUE THREAD

**Issue by RobertoSnap** [ethereum-ts/TypeChain#272]
Creating a tool. In this tool, I want to give developers the possibility to extend the class generated. 

What do you think of the possibility to add a prefix or postfix optional arg (especially interested for ethers-v5)?

With some design input maybe I can make a PR for this.

**Comment by RobertoSnap** [comment]
nhaa. wait. Does not seem that those classes generated are extenable.

**Comment by krzkaczor** [comment]
It seems like you case is quite specific. I suggest creating your own target. You can pick one of the already created ones and tweak it to your needs.
