### ISSUE TITLE
ethers 5.0.9 breaking change

### ISSUE THREAD

**Issue by tuler** [ethereum-ts/TypeChain#277]
Something changed in `ethers@5.0.9` that broke the code generated by `@typechain/ethers-v5`
The error message below was edit to remove references to my code, replacing the contract name with `<ContractName>` and method signature with `<methodSignature>`.

```
Interface '<ContractName>Interface' incorrectly extends interface 'Interface'.
  Types of property 'functions' are incompatible.
    Type '{ "<methodSignature>": FunctionFragment; }' is not assignable to type '{ [name: string]: FunctionFragment; }'.
      Property '"<methodSignature>"' is incompatible with index signature.
        Type 'import("./node_modules/@ethersproject/abi/lib/fragments").FunctionFragment' is not assignable to type 'import("./node_modules/ethers/node_modules/@ethersproject/abi/lib/fragments").FunctionFragment'.
          Types of property 'gas' are incompatible.
            Type 'import("./node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber | undefined' is not assignable to type 'import("./node_modules/ethers/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber | undefined'.
              Property 'toJSON' is missing in type 'import("./node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber' but required in type 'import("./node_modules/ethers/node_modules/@ethersproject/bignumber/lib/bignumber").BigNumber'.ts(2430)
bignumber.d.ts(33, 5): 'toJSON' is declared here.
```

It is probably related to this change:
https://github.com/ethers-io/ethers.js/commit/8facc1a5305b1f699aa3afc5a0a692abe7927652

**Comment by zemse** [comment]
I just confirmed this issue by upgrading to `ethers@5.0.12` from `5.0.7`.

The issue is that there are two `@ethersproject/bignumber` installations of different versions. In my case I had `./node_modules/@ethersproject/bignumber@5.0.1` and `./node_modules/ethers/node_modules/@ethersproject/bignumber@5.0.6`.

I fixed this by simply doing `npm i @ethersproject/bignumber@latest`.

Looks like when upgrading ethers versions, only `ethers` bucket is upgraded. So if we are importing anything from `@ethersproject` bucket, it is likely importing from older version. I think this is a problem. For example, a severe fix is released in ethers.js. People just install the latest version thinking it's done and forget.  They're still vulnerable

@ricmoo Can something be done to ensure one can easily upgrade all of ethers.js?

**Comment by ricmoo** [comment]
I will look into this shortly. I didn’t think there was any changes that required a lock-version release. But this error usually indicates this...

**Comment by ricmoo** [comment]
(Oh. Just realized this wasn’t on my repo, I was just tagged. Sorry.)

**Comment by ricmoo** [comment]
The later version of ethers has had all versions locked, so depending on `^5.0.13` should solve this problem.

Sorry for the inconvenience.

**Comment by tuler** [comment]
I tried migrating from `5.0.8` to `^5.0.13` and it still doesn't work.
Can you confirm it works for you? @zemse ?

**Comment by ricmoo** [comment]
Can you upload your package-lock.json to a gist and include it? Or send it to me@ricmoo.com?

It should be forced to pull the latest version of the ethers BigNumber module...

**Comment by tuler** [comment]
I sent my `yarn.lock` to your email. thanks.

**Comment by ricmoo** [comment]
@tuler How did you install ethers? I don't see it in that yarn.lock file and the versions of BigNumber don't match the version locked in the package.json. If you added it to your package.json, did you remember to run `npm install` (or the yarn equivalent) to update the lock file?

**Comment by BryceDoganer** [comment]
`npm i @ethersproject/bignumber@latest` worked for me.

**Comment by krzkaczor** [comment]
I am closing this for now. Please reopen if it still doesn't work.

**Comment by ricmoo** [comment]
Oh! Sorry, I lost track of this issue and was trying to find it.

The new build system for ethers now locks the umbrella package versions for all dependencies. So if you depend on the `ethers` package directly, this should never happen again. :)
