### ISSUE TITLE
 Proposal: add exportable return types

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [ethereum-ts/TypeChain#284]
Hi, would it be possible to make return types exportable or was it already discussed before?

I think it could be useful. For example, in one of my projects i have function `getReserves(tokenA: string, tokenB: string) => someType`, that's basically wrapper around generated by `TypeChain` contract method:
```
getReserves(): NonPayableTransactionObject<{
      reserve0: string;
      reserve1: string;
      blockTimestampLast: string;
      0: string;
      1: string;
      2: string;
}>
```
`someType` is identical to type specified in `getReserves` method signature, so, in that case, if that type would be exported, it would be possible to reuse it.

**Comment by krzkaczor** [comment]
I think we already export more complicated types like events or structs. I think doing this for every type would be very noisy. 

Perhpaps you can extract this type using type level programming like:
```typescript
type TxReturnType<T> = T extends NonPayableTransactionObject<infer PAYLOAD> ? PAYLOAD : never;
type Ret = TxReturnType<ReturnType<contract.method>>
```

This is handwritten so probably needs some fixing.
