### ISSUE TITLE
Improve CI

### ISSUE THREAD

**Issue by krzkaczor** [ethereum-ts/TypeChain#292]
1. Migrate to GHA
2. Ensure that it runs on forks correctly. For some reason, CI didn't run on: https://github.com/ethereum-ts/TypeChain/pull/290

**Comment by rryter** [comment]
I recently migrated one of my repos to GHA.
https://github.com/rryter/smart-vault/blob/master/.github/workflows/ci-cd.yml

Do you want to this yourself or do you mind if I give it a shot?

**Comment by krzkaczor** [comment]
Thanks @rryter but I would prefer to do it myself as I want to try few new ideas, but thanks for reaching out :)
