### ISSUE TITLE
Typechain & ethers - Wrong Function Fragments

### ISSUE THREAD

**Issue by nivida** [ethereum-ts/TypeChain#295]
The generated types for the function fragments of a contract object are wrong. As soon as an argument is of type ``tuple`` is the function fragment name/signature not correct. As I have seen during a quick check that TypeChain does not parse the whole ``tuple`` it just uses the type ``tuple``.. means: ``myFunction(tuple)`` instead of e.g.: ``myFunction((uint, address))``. The same behavior is for event fragments.

**Comment by krzkaczor** [comment]
Hey @nivida, can you prepare a solidity file or ABI that would reproduce this problem?
