### ISSUE TITLE
SyntaxError: '=' expected

### ISSUE THREAD

**Issue by PaulRBerg** [ethereum-ts/TypeChain#301]
## Description
I saw the recent v4 release and I wanted to upgrade to it in my [solidity-template][1], but there is no CHANGELOG explaining what changed since v2 or v3.

Simply installing typechain@4.0.0 and @typechain/ethers-v5@3.0.0 gets me this error:

```
SyntaxError: '=' expected. (8:15)
   6 |   import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";
   7 |
>  8 |   import type { Greeter } from "./Greeter";
     |               ^
   9 |
  10 |   export class GreeterFactory extends ContractFactory {
```

[See the full stack trace here][2].

## How to Reproduce

1. Clone [paulrberg/solidity-template][1]
2. Switch to the [typechain-v4][3] branch
3. Install dependencies with yarn
4. Run `yarn typechain`

[1]: https://github.com/paulrberg/solidity-template
[2]: https://gist.github.com/PaulRBerg/59ebbc359844ada0c5f0a3b157d5878d
[3]: https://github.com/PaulRBerg/solidity-template/tree/typechain-v4

**Comment by quezak** [comment]
@PaulRBerg do the [typechain package](https://github.com/ethereum-ts/TypeChain/releases) release notes include the necessary info?

@krzkaczor we should add release notes for target packages too

**Comment by PaulRBerg** [comment]
> Do the typechain package release notes include the necessary info?

Not really. It's not clear from either the following statement:

> Do not camel case contract names

Or #293 what exactly I should do to make the upgrade to TypeChain v4.

**Comment by krzkaczor** [comment]
It's was actually a previous release: https://github.com/ethereum-ts/TypeChain/releases/tag/typechain%403.0.0

You are running an old TS version (i think before 3.7) that doesn't support type imports (`export type` syntax). Upgrading typescript should fix this problem.

Please reopen if it still doesn't work.

**Comment by PaulRBerg** [comment]
Thanks @krzkaczor! I think it'd be worth it to mention that TypeChain v4 only works with TypeScript v4. Lots of people are still using TypeScript v3.

**Comment by quezak** [comment]
@PaulRBerg which TS version did you try before? I think it only requires TS3.7. There is a peer dependency for `typechain: ^4.0.0`, I was also confused by that at first :smile:

Anyway, we'll add a peer dependency on `typescript` too so you'll get warned if your version is too old.

**Comment by PaulRBerg** [comment]
v3.9.7: https://github.com/PaulRBerg/solidity-template/blob/4e7d7b3907082f34d951a51600e57e735af8beef/package.json#L45

**Comment by krzkaczor** [comment]
Fixed in: [`0f661c6` (#300)](https://github.com/ethereum-ts/TypeChain/pull/300/commits/0f661c68ae2c27fb1b2caf135a7bd873e51a7263)

Btw. bonus q: is it possible in semver to say that everything above 3.8 including next major is fine?

**Comment by PaulRBerg** [comment]
> Btw. bonus q: is it possible in semver to say that everything above 3.8 including next major is fine?

I think that `^3.8.x` should do the trick:

https://jubianchi.github.io/semver-check/#/constraint/^3.8.x

**Comment by quezak** [comment]
`^3.8.x` alows `3.9` -- I think @krzkaczor wanted to allow `4.0` too. I don't think that's possible with a single operator if you still want to _not_ allow `5.0`.

**Comment by PaulRBerg** [comment]
Oh, yes. That doesn't look like it's possible:

https://github.com/semver/semver/issues/395

**Comment by krzkaczor** [comment]
Just to clarify - I want to match 3.8, 3.9, 4.x even future 5.x and 21.x releases. 

I think it's simply not possible because this is not how semver works :/ Obviously, TS doesn't comfort to semver spec so it is what it is.

**Comment by quezak** [comment]
@krzkaczor can't you just specify `>=3.8.0` then?

**Comment by krzkaczor** [comment]
Oh, actually it seems that it works (at least according to: https://jubianchi.github.io/semver-check/#/%3E%3D3.8.0/5 ) KISS! :D
