### ISSUE TITLE
Add type support for ethers v5 queryFilter

### ISSUE THREAD

**Issue by zemse** [ethereum-ts/TypeChain#303]
```solidity
event Transfer(address sender, address receiver, uint256 value);
```

```ts
const filter = contractInst.filters.Transfer(); // TransferFilter

const logs = await contractInst.queryFilter(filter) // Overloaded for each filter

logs[0].args // before `any`, but after this feature it should be `{sender: string, receiver: string, value: BigNumber}`
```

I'll give this a shot while doing my next project starting probably end of this month or next month.

**Comment by quezak** [comment]
Sounds like a good idea. You'll probably have to add a special `EventFilter` subtype for each event. Or make it a generic type based on the event param types, so then the new function would simply be like `queryFilter<PT>(TypedEventFilter<PT>): Promise<Array<TypedEvent<PT>>>`. Or another approach is it makes the resulting code easier to use :+1:

**Comment by Siegrift** [comment]
@zemse Shouldn't this be closed?
