### ISSUE TITLE
truffle-v5: Some properties of `Truffle.ContractInstance` are missing

### ISSUE THREAD

**Issue by odanado** [ethereum-ts/TypeChain#315]
For example, properties of `Overloads` of `packages/target-truffle-v5-test/test/Overloads.test.ts` are different between type and runtime.

type:
<img width="496" alt=" 2020-12-06 21 38 22" src="https://user-images.githubusercontent.com/6040962/101280242-5feb8b80-380b-11eb-8b1f-5f45f5675e6a.png">

runtime:
<img width="165" alt=" 2020-12-06 21 21 25" src="https://user-images.githubusercontent.com/6040962/101279894-084c2080-3809-11eb-8e8f-afc9ad028fef.png">

missing properties:
- abi
- allEvents
- ~getPastEvents~
- send
- sendTransaction

**Comment by odanado** [comment]
I try to solve this issue

**Comment by quezak** [comment]
Great! We'll be waiting for a PR :)

**Comment by julianlen** [comment]
Hi there!

 is it the 'setProvider' method missing too ?

**Comment by odanado** [comment]
@julianlen 
No.
The `contract of Truffle` and the` contract` of web3.js are different.

**Comment by odanado** [comment]
@krzkaczor 
`${c.name}Instance` inherits from `Truffle.ContractInstance`.
ref: https://github.com/ethereum-ts/TypeChain/blob/0d75de7c26e976ad26a566611a4d7c89473317e6/packages/target-truffle-v5/src/codegen/ contracts.ts#L49

I found out that there are two ways to resolve this issue.

- Update `truffle-typing`
- Update `@truffle/contract`

## Update `truffle-typing`
This package is deprecated. However, this package belongs to `ethereum-ts`, so it is easy to fix

## Update `@truffle/contract`
`@truffle/contract` provides a formal type definition for `contract` objects. However, the type definition differs from the runtime properties in some ways, and is wrong. To fix it, I need to make a pull request to trufflesuite, but it is very difficult.

Which way do you think is better?

**Comment by krzkaczor** [comment]
> Update truffle-typing

Generated contracts don't use `truffle-typings` anymore so even when you fix it there it won't have any effect.

> Update @truffle/contract

This seems to be the right way. I am sure that the truffle folks will be happy to help you.

There is also a third way: we can generate missing methods as part of TypeChain generated but I would consider it a last resort fix.

> To fix it, I need to make a pull request to trufflesuite, but it is very difficult.

Why do you consider it such a difficult task? I would expect a very similar difficulty level as updating `@truffle/contracts`. Or do you have a process related difficulties in mind?

**Comment by odanado** [comment]
> Generated contracts don't use truffle-typings anymore so even when you fix it there it won't have any effect.

No.
`Truffle.Contract` of https://github.com/ethereum-ts/TypeChain/blob/0d75de7c26e976ad26a566611a4d7c89473317e6/packages/target-truffle-v5/src/codegen/contracts.ts#L29 is `Contract` of https://github.com/ethereum-ts/truffle-typings/blob/9dec2bec9335b6aba4fa64ea41995d776c455ec2/index.d.ts#L67.


>  do you have a process related difficulties in mind?

Yes.
I was considered about the effort involved in reviewing a pull request.

I will try to create a pull request to `@truffle/contract`.

**Comment by krzkaczor** [comment]
Okay, I figured it out. the `Truffle` namespace (and thus `Truffle.Contract`) is part of truffle-v5 target: https://github.com/ethereum-ts/TypeChain/blob/master/packages/target-truffle-v5/static/types.d.ts

So I remember deprecating `truffle-typings` and moving them directly to typechain so it's easier to use. It should be enough to tweak these definitions.

**Comment by odanado** [comment]
Oh. I didn't know `packages/target-truffle-v5/static/types.d.ts`.
Well then, I will update `packages/target-truffle-v5/static/types.d.ts`.

**Comment by quezak** [comment]
> Okay, I figured it out. the `Truffle` namespace (and thus `Truffle.Contract`) is part of truffle-v5 target: https://github.com/ethereum-ts/TypeChain/blob/master/packages/target-truffle-v5/static/types.d.ts
> 
> So I remember deprecating `truffle-typings` and moving them directly to typechain so it's easier to use. It should be enough to tweak these definitions.

This might be worth noting in the truffle-typings package README, so next time we (and the users) know 😅

**Comment by krzkaczor** [comment]
Released: https://github.com/ethereum-ts/TypeChain/releases/tag/%40typechain%2Ftruffle-v5%404.0.1

@odanado Thanks for this!
