### ISSUE TITLE
Truffle typings needed with unupdated web3 packages

### ISSUE THREAD

**Issue by julianlen** [ethereum-ts/TypeChain#316]
Hi!

I read in the README that to use Truffle target is needed to have the truffle-typings package. The problem's that truffle-typings uses web3 1.2.6 packages. Is there a possibility to update those web3 packages to 1.3.0?

Thank you in advance

**Comment by quezak** [comment]
Which package versions are you using?

If you check the [truffle-typings repo](https://github.com/ethereum-ts/truffle-typings), it says the package is deprecated as TypeChain v2 automatically generates the required typings.

@krzkaczor the README for the truffle target needs to be updated -- remove the typings package reference, and update example links (I'd do it immediately via github UI, but it says I can't if I'm not on a branch, so I can't right now 😅 )

**Comment by julianlen** [comment]
Thanks for the fast response!

I'm using:

```
typechain --target trufflehotfix './build/contracts/**/*.json'
    "typechain": "1.0.5",
    "typechain-target-trufflehotfix": "0.0.4-alpha",
```
Which I know those get old. In the other hand, I read the typings package reference on the READMA and that's why I got confused. In addition, I tried to use Truffle-v5 and there were a lot of incompatibility errors. I'll try again and comment here what happened.

**Comment by krzkaczor** [comment]
You don't need `truffle-typings` anymore as TypeChain generates it for you. Can you tell me where did you find this info?

When in doubt check out examples: https://github.com/ethereum-ts/TypeChain/tree/master/examples

**Comment by julianlen** [comment]
I found it on the README in Targets section

It says:
```
Truffle v4 / v5
Truffle target is great when you use truffle contracts already. Check out truffle-typechain-example for more details. It require installing typings for truffle library itself.

Now you can simply use your contracts as you did before and get full type safety, yay!
```

I'll try to use truffle-v5 target

**Comment by krzkaczor** [comment]
Thanks! This seems outdated. I will fix it today.

**Comment by julianlen** [comment]
OK, just to know, this kind of problem:
```
node_modules/@truffle/contract-schema/spec/index.d.ts:72:3 - error TS2411: Property 'contractName' of type 'string | undefined' is not assignable to string index type 'string | number | boolean | any[] | { [k: string]: any; }'.

72   contractName?: string;
```

is it because I'm importing more than one package of Truffle?

**Comment by krzkaczor** [comment]
yeah... i think so... Compare your deps with examples - I am sure that they work.

**Comment by quezak** [comment]
@julianlen best would be to update TypeChain and typechain-target-truffle to the latest version (and a corresponding version of truffle). If you encounter an error in the typings after that, feel free to open a new issue.
