### ISSUE TITLE
Unable to build .d.ts files

### ISSUE THREAD

**Issue by sdelvalle57** [ethereum-ts/TypeChain#319]
Hey guys, Im using typechain with ether-v5 to generate some typings, however I cannot get to build my package as the .d.ts files wont export.

This is my package.json scripts, see `contracts:type`:
![image](https://user-images.githubusercontent.com/12821552/105521377-cd635680-5ca9-11eb-8545-4e1c218df5f5.png)

All types get generated as expected:
![image](https://user-images.githubusercontent.com/12821552/105520666-fb946680-5ca8-11eb-9fbb-d22f3cbe637c.png)

The issue comes when I run `npm run build`, this is what gets built:
![image](https://user-images.githubusercontent.com/12821552/105520852-339ba980-5ca9-11eb-9145-09175c02d93a.png)

As you can see , there are some missing files specially the `.d.ts`, checking the content of the `index.d.ts` built file:
![image](https://user-images.githubusercontent.com/12821552/105521072-72c9fa80-5ca9-11eb-91a7-6ff1013e5fac.png)

This is my tsconfig file:
![image](https://user-images.githubusercontent.com/12821552/105521256-a3119900-5ca9-11eb-90b2-cf50bd4da987.png)

Any workaround?

Regards

**Comment by zemse** [comment]
When you build your project, you have to seperately copy the `*.d.ts` files to the build directory. A script can be written or you can use a package ([example](https://github.com/KMPARDS/eraswap-sdk/blob/master/package.json#L11)).

**Comment by stevemao** [comment]
@zemse Just wondering if this is documented/explained somewhere in the docs? Took me a few days to find this. Thanks.

**Comment by zemse** [comment]
This is a typescript related design https://github.com/Microsoft/TypeScript/issues/5112#issuecomment-145633791

But yes having a text in the Typechain docs will save the time of some in the future. Would you like to contribute?
