### ISSUE TITLE
Support for truffle v5 - use contract at specific address

### ISSUE THREAD

**Issue by ducquangkstn** [ethereum-ts/TypeChain#323]
The generated types don't have function for use contract at a specific address:
https://www.trufflesuite.com/docs/truffle/getting-started/interacting-with-your-contracts#use-a-contract-at-a-specific-address.

```typescript
import BN from 'bn.js'
import { ERC20TokenContract } from '../src/types/ERC20Token'

const ERC20Token: ERC20TokenContract = artifacts.require('ERC20Token')

contract('ERC20Token', (accounts: string[]) => {
  it('test', async () => {
    let token = await ERC20Token.new('tst', 'test', new BN(18))
    await token.supply(accounts[0], accounts[1], new BN(10).pow(new BN(18)))
    console.log(await token.totalSupply())
    // typechain does not support this
    // let token2  = await ERC20Token.at(token.address);
  })
})
```

**Comment by quezak** [comment]
@ducquangkstn would you like to prepare & test a PR? We're more versed in using ethers here :)
[This is the relevant file](https://github.com/ethereum-ts/TypeChain/blob/master/packages/target-truffle-v5/src/codegen/contracts.ts), it should be a simple matter of adding a static method declaration. You could even add some of the other [contract static methods](https://www.trufflesuite.com/docs/truffle/reference/contract-abstractions#contract-abstraction-api).

**Comment by forshtat** [comment]
@ducquangkstn it seems like 'at' and some other shared contract methods are defined in a generated 'types.d.ts' file, isn't that so?

**Comment by ducquangkstn** [comment]
Well after debugging, I found 2 namespace with the same name `Truffle` in file `types.d.ts` and `index.d.ts`
And the file Greeter.d.ts is using the namespace from **index.d.ts**
```typescirpt
export interface GreeterContract extends Truffle.Contract<GreeterInstance> {
}
```

a way to fix this is including `/// <reference path="./types.d.ts" />` at the start of the generated file Greeter.d.ts.
But I not sure about this approach

**Comment by ducquangkstn** [comment]
P/s: I using truffle by hardhat and typechain

**Comment by ducquangkstn** [comment]
After a while, I figure out I must include typechain outDir in `tsconfig.json`

I add a PR to help others with the same issue
https://github.com/ethereum-ts/TypeChain/pull/352
