### ISSUE TITLE
convert the expression to 'unknown' first

### ISSUE THREAD

**Issue by tuler** [ethereum-ts/TypeChain#328]
While generating code for a solidity interface I get the following error:

```
Conversion of type 'Contract' to type '<ContractName>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'Contract' is missing the following properties from type '<ContractName>': <list of methods>, and <N> more.ts(2352)
```

The template comes from the line below.
https://github.com/ethereum-ts/TypeChain/blob/7a02d990a0dc7fc7172c1fdef673115778855f04/packages/target-ethers-v5/src/codegen/index.ts#L193

It works If I replace this:
```typescript
return new Contract(address, _abi, signerOrProvider) as <ContractName>;
```

With this:
```typescript
return (new Contract(address, _abi, signerOrProvider) as unknown) as <ContractName>;
```

But I'm not sure what is the real solution or error here.

My dependencies are:

```
    "@typechain/ethers-v5": "^6.0.0",
    "typechain": "^4.0.2",
    "typescript": "^4.1.5"
```

My `tsconfig.json` is as follow:

```json
{
    "compilerOptions": {
        "declaration": true,
        "esModuleInterop": true,
        "module": "commonjs",
        "outDir": "dist",
        "resolveJsonModule": true,
        "strict": true,
        "target": "es5"
    }
}
```

**Comment by krzkaczor** [comment]
This is odd indeed. Frankly, I think we should have incorporate fix to the generated code as you suggested (maybe I would go with `any` cast instead of `unknown` as it's more idiomatic IMO)). Are you interested in making a PR fixing this?

Can you share your `ethers` version?

Also we have example for ethers-v5 which I am sure that works: https://github.com/ethereum-ts/TypeChain/tree/master/examples/ethers-v5

**Comment by tuler** [comment]
After deleting my `yarn.lock` and re-running yarn the error disappeared. Maybe it was an outdated ethers dependency.

**Comment by quezak** [comment]
Yeah, IIRC there was a "somewhat breaking" typings change in ethers' own contract typings, which should be gone in the current release.
Our contract typings are just a "more specified" version of ethers `Contract` typings, so if the compiler says types don't match it would signal a problem (probably incompatible changes in ethers contract typings).
