### ISSUE TITLE
generated typescript typing broken: must be unknown first

### ISSUE THREAD

**Issue by robert-e-davidson3** [ethereum-ts/TypeChain#330]
When building the generated typescript, I get this error: 

```
TS2352: Conversion of type 'Contract' to type 'AccountLoader' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
```

Generated code:

```
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { AccountLoader } from "../AccountLoader";

export class AccountLoader__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AccountLoader {
    return new Contract(address, _abi, signerOrProvider) as AccountLoader;
  }
}

const _abi = <omitted for concision>
```

node version v12.19.0
ts-node version v9.0.0
yarn version 1.22.5

**Comment by robert-e-davidson3** [comment]
nevermind, typescript version incompatibility

**Comment by robert-e-davidson3** [comment]
This is still a problem with typescript version 4.2.2.

**Comment by quezak** [comment]
@robert-e-davidson3 most likely the code is correct but there were some incompatible changes in ethers. Can you update all ethers packages and try again? See also a similar issue in #328

**Comment by robert-e-davidson3** [comment]
Upgrading ethers 5.0.15 -> 5.0.31 fixed the issue!

**Comment by quezak** [comment]
@krzkaczor we should bump the minimum ethers version required so this doesn't happen. IIRC it's 5.0.17 or 19

**Comment by krzkaczor** [comment]
It's broken again on `5.0.32`.

I've submitted a PR that should improve this situation: https://github.com/ethereum-ts/TypeChain/issues/330

**Comment by robert-e-davidson3** [comment]
You linked this issue. PR: https://github.com/ethereum-ts/TypeChain/pull/347
