### ISSUE TITLE
Unused type parameters in typechain/ethers-v5 6.0.1

### ISSUE THREAD

**Issue by CodeSandwich** [ethereum-ts/TypeChain#335]
After bumping `@typechain/ethers-v5` from `5.0.5` to `6.0.1` my project stops compiling when `noUnusedParameters` compiler option is enabled in TS 4.0.1.

The TypeChain-generated file `commons.ts` triggers an error:
```ts
contract-bindings/ethers/commons.ts:8:34 - error TS6205: All type parameters are unused.

8 export interface TypedEventFilter<EventArgsArray, EventArgsObject>
```
This is its body:
```ts
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { EventFilter, Event } from "ethers";
import { Result } from "@ethersproject/abi";

export interface TypedEventFilter<EventArgsArray, EventArgsObject>
  extends EventFilter {}

export interface TypedEvent<EventArgs extends Result> extends Event {
  args: EventArgs;
}

export type TypedListener<
  EventArgsArray extends Array<any>,
  EventArgsObject
> = (
  ...listenerArg: [
    ...EventArgsArray,
    TypedEvent<EventArgsArray & EventArgsObject>
  ]
) => void;
```

**Comment by zemse** [comment]
The generics in `TypedEventFilter` are unused (in self object) but needed to carry forward the information what the `queryFilter` should return when the filter is passed in it. Rn I think we might need to add `// tslint:disable-next-line:no-unused-variable`. @krzkaczor @quezak could there be a better solution?

**Comment by quezak** [comment]
@zemse It's not tslint, it's tsc compilation. We need to rename the params to `TypedEventFilter<_EventArgsArray, _EventArgsObject>` so tsc allows it.

**Comment by krzkaczor** [comment]
Released as: https://github.com/ethereum-ts/TypeChain/releases/tag/%40typechain/ethers-v5%406.0.2

Thanks, @zemse and @quezak for figuring out a fix so quickly :)

**Comment by CodeSandwich** [comment]
Thank you! It was lightning fast :)
