### ISSUE TITLE
[ethers] Expose ABI in generated code

### ISSUE THREAD

**Issue by ryanleecode** [ethereum-ts/TypeChain#344]
I'm using `deployMockContract` from [@ethereum-waffle/mock-contract](https://www.npmjs.com/package/@ethereum-waffle/mock-contract) and it requires an ABI for it to be called. Typechain currently doesn't expose this but the abi constant is in the generated factory file. 

Can there be a configuration option to expose the ABI?

**Comment by quezak** [comment]
Technically it could be done, but I'm thinking if it would be good design 🤔

In such a specific case where you need access to the raw ABI, maybe it's easier to just read it from the contract JSONs that you have already?
Like `import { abi as yourContractAbi } from 'your/contracts/build/dir/YourContract.json`

@krzkaczor WDYT?

**Comment by quezak** [comment]
we can also ask @sz-piotr who works on Waffle -- do you have any advice or opinions in this case?
(some day maybe  a collab package with Typechain? 😉)

**Comment by ryanleecode** [comment]
Actually i guess if i just turn on `resolveJsonModule` in tsconfig.json, I can still get types from the compiled artifacts. So this can just "work". Really long import paths though :c.

**Comment by sz-piotr** [comment]
I am longer a maintainer of waffle. Please ask @marekkirejczyk, thanks :)

**Comment by quezak** [comment]
> Really long import paths though :c.

If that's the only concern then you can add a [path alias/mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) to your tsconfig -- I use that a lot in my projects, including an entry for contract JSONs like `"@contract-abis/*": ["....build/contracts/*"]`

**Comment by robert-e-davidson3** [comment]
This would be nice. I only need it for tests as well but if this does leak into production, I'd prefer to only bundle the abi once.

**Comment by quezak** [comment]
@ryanleecode just to confirm, which target are you using?

**Comment by ryanleecode** [comment]
> @ryanleecode just to confirm, which target are you using?

ethers-v5

**Comment by quezak** [comment]
I agree that this would be useful in some cases. I actually used to import the json files too, before the factory classes were added to the ethers target here. @krzkaczor what do you think?

How about adding the data as `abi` and `bytecode` static readonly properties of the factory class?
IMO it feels better than exporting very generic names like `abi` or `bytecode` from each factory file.

**Comment by krzkaczor** [comment]
> How about adding the data as abi and bytecode static readonly properties of the factory class?
IMO it feels better than exporting very generic names like abi or bytecode from each factory file.

Yes I think the only way to make this useful is to expose it as part of the factory class (not module). 

I am fine with this change. The only problem that I see is that hardhat users confuse these factories often with factories from hardhat but I am planning to address it in a separate ticket (https://github.com/ethereum-ts/TypeChain/issues/359).

**Comment by krzkaczor** [comment]
@ryanleecode are you up to make a PR with this?

**Comment by ryanleecode** [comment]
Gonna have to pass on this. I'll leave it up to you fellas
