### ISSUE TITLE
Hardhat plugin always rebuilds typechain artifacts

### ISSUE THREAD

**Issue by Remscar** [ethereum-ts/TypeChain#346]
Bug with the `@typechain/hardhat` package.

When using the typechain plugin for hardhat, typechain artifacts will always be rebuilt, even if the smart contracts haven't changed.
While this isn't breaking, it adds an additional few seconds to every time a hardhat command is run.

Is there any way that the plugin could detect that the typechain artifacts are out of date? Perhaps check the modified time of the artifacts compared to the source solidity files and only regenerate if needed?

I'd be interested in fixing this and submitting it as a PR if it's not already in progress.

**Comment by krzkaczor** [comment]
Good point 👍 

@alcuadrado any suggestions? Perhaps we could use the same machinery as hardhat uses internally to realize which files need recompiling.

**Comment by quezak** [comment]
The issue isn't related only to hardhat target I think -- other targets could also benefit of only building the needed files.
In my project that uses the ethers target, I have a bash script with some heuristics for that (get contract names from sol files with grep&sed, then check if the expected resulting files exist and are up to date). Maybe such behavior could be integrated into Typechain in some level? Probably hidden behind a flag, to avoid weird edge cases -- for example when someone switches to another git branch where the contract files are different but older, which wouldn't trigger a rebuild.

**Comment by quezak** [comment]
btw: here are the scripts I mentioned if anyone's interested: https://gist.github.com/quezak/b0cd46ec2d378a34edf0734505a5725e

**Comment by alcuadrado** [comment]
> @alcuadrado any suggestions? Perhaps we could use the same machinery as hardhat uses internally to realize which files need recompiling.

Pretty sure you can. Will think about it and get back to this tomorrow.

**Comment by Remscar** [comment]
Wanted to come back and say thank you so much for adding this feature. Really appreciate it!
