### ISSUE TITLE
Build empty contract

### ISSUE THREAD

**Issue by sshmaxime** [ethereum-ts/TypeChain#366]
As of now, types aren't created when a contract is empty, i.e:

```
contract myContract {}
```

That would be nice if it still build types for it

**Comment by quezak** [comment]
Can you elaborate how would typings for such a contract be useful? I think you can just use ethers/truffle's plain Contract class because there's nothing to be added with more precise typings.

**Comment by sshmaxime** [comment]
You got a point, didn't think about the fact I could use the default Contract class, mb. Closing.
