### ISSUE TITLE
Hardhat with external dependency

### ISSUE THREAD

**Issue by ducquangkstn** [ethereum-ts/TypeChain#367]
Hi I am using typeChain with hardhat.
I try to import dependency (json file).

Is there any way to include json path (in node_modules folder) when generating typeChain files

**Comment by krzkaczor** [comment]
I think currently there is no way to achieve it. Thanks for raising this. I will make sure to add it in: https://github.com/ethereum-ts/TypeChain/pull/363

**Comment by krzkaczor** [comment]
btw. as a quick workaround you can always run TypeChain again as a separate build step (and for example set `outDir` to something else). Ugly but it should work.

**Comment by ducquangkstn** [comment]
Yeah, right now, I am doing that way.
The thing is it will create 2 typechain folders (1 for my repo and 1 for the library), so it is kind of ugly solution

**Comment by krzkaczor** [comment]
Sorry, I decided to drop it from the release. Feel free to pick it up.

**Comment by moodysalem** [comment]
people who use the Uniswap V3 npm artifacts probably want this

**Comment by omarish** [comment]
> people who use the Uniswap V3 npm artifacts probably want this

+1. I ended up doing this as a workaround:

https://github.com/omarish/uniswap-v3-staker/blob/55c0b03f68eef947b41205ce6623c0f3f13292ad/hardhat.config.ts#L9-L32

**Comment by ducquangkstn** [comment]
> people who use the Uniswap V3 npm artifacts probably want this

Actually, I work at Kyber. :))))
But we built a lot of bridge reserve and tried to publish our artifacts as well

**Comment by krzkaczor** [comment]
The good news is that @ducquangkstn 's fix looks good. Just needs a little bit of tweaking so this should be done soon.
