### ISSUE TITLE
hardhat task from dedicated file -- fails to build with Typechain import

### ISSUE THREAD

**Issue by rad-p** [ethereum-ts/TypeChain#371]
Problem:
cant use `hardhat` if task imports typechain contract; 
task has to be defined in dedicated file and imported into hardhat config;

Reproduce:
https://github.com/rad-p/TypeChain/commit/128b6020cb73c9d5521a0e037bdec0efa9d8c24b

can't use `yarn hardhat`

call:
```
 .../TypeChain/examples/hardhat
❯ yarn hardhat typechain

yarn run v1.22.10
$ /home/mr13/projects/ethereum-ts/TypeChain/examples/hardhat/node_modules/.bin/hardhat typechain
An unexpected error occurred:

tasks/counter.ts:2:23 - error TS2307: Cannot find module '../typechain' or its corresponding type declarations.

2 import {Counter} from "../typechain";
                        ~~~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

env:

```
❯ node --version
v14.16.1
 
❯ yarn --version
1.22.10

```

**Comment by julianlen** [comment]
Check the `tsconfig.json` file if it has `  "include": ["./hardhat.config.ts","./scripts","src/**/*", "**/*.ts","./test", **"typechain/**/***"],`

The same for `hardhat.config.ts` check if you are importing `import "@typechain/hardhat"`

**Comment by krzkaczor** [comment]
Please refer to this example: https://github.com/ethereum-ts/TypeChain/tree/master/examples/hardhat

As @julianlen mentioned, probably it's `tsconfig.json` misconfiguration.

**Comment by mr13tech** [comment]
in example it is still an issue

```
➜ git clone git@github.com:ethereum-ts/TypeChain.git
Cloning into 'TypeChain'...
remote: Enumerating objects: 7939, done.
remote: Counting objects: 100% (1236/1236), done.
remote: Compressing objects: 100% (577/577), done.
remote: Total 7939 (delta 760), reused 1038 (delta 642), pack-reused 6703
Receiving objects: 100% (7939/7939), 3.29 MiB | 595.00 KiB/s, done.
Resolving deltas: 100% (4999/4999), done.

~/projects took 9s 
➜ cd TypeChain/examples/hardhat

TypeChain/examples/hardhat on  master is 📦 v1.0.0 via ⬢ v15.14.0 
➜ yarn 
yarn install v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
✨  Done in 7.58s.

TypeChain/examples/hardhat on  master is 📦 v1.0.0 via ⬢ v15.14.0 took 8s 
➜ yarn test
yarn run v1.22.10
$ hardhat test
Compiling 2 files with 0.6.8
contracts/Counter.sol: Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.

Compilation finished successfully
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!
An unexpected error occurred:

test/counter.ts:5:43 - error TS2307: Cannot find module '../typechain' or its corresponding type declarations.

5 import { Counter__factory, Counter } from "../typechain";
                                            ~~~~~~~~~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

TypeChain/examples/hardhat on  master is 📦 v1.0.0 via ⬢ v15.14.0 took 6s 
➜ yarn test
yarn run v1.22.10
$ hardhat test
Creating Typechain artifacts in directory typechain for target ethers-v5
Successfully generated Typechain artifacts!


  Counter
    count up
countUp: count = 0
      ✓ should count up (76ms)
    count down
countDown: count = 0
      ✓ should fail due to underflow exception (96ms)
countUp: count = 0
countDown: count = 1
      ✓ should count down (121ms)


  3 passing (1s)

✨  Done in 5.91s.
```

**Comment by krzkaczor** [comment]
@mr13tech ahh yes I think this is a problem with `ts-node`. You need to ensure that types are generated before running tests. Hardhat team tries to come up with a fix for this AFAIK.

**Comment by paulrberg** [comment]
Any updates on this? I am running into the same issue:

https://github.com/paulrberg/contracts/runs/3240059718?check_suite_focus=true

**Comment by krzkaczor** [comment]
@alcuadrado I think you had some fix in mind?

**Comment by alcuadrado** [comment]
There's a workaround that's running `TS_NODE_TRANSPILE_ONLY=1 npx hardhat typechain` first.

We are looking for ways to fix this, but it's not clear yet how, nor we can prioritize it yet.

**Comment by tuler** [comment]
> TS_NODE_TRANSPILE_ONLY=1 npx hardhat typechain

This workaround does not work for me.

The only way I can workaround from this is to `require` the type dynamically, losing the purpose of having the type information.

**Comment by alcuadrado** [comment]
Can you post a link to a repo so that I can take a look, @tuler ?

**Comment by tuler** [comment]
> Can you post a link to a repo so that I can take a look, @tuler ?

I created this demo project:
https://github.com/tuler/hardhat-typechain-371

Thanks in advance for looking it up.

**Comment by roberts-ivanovs** [comment]
Is there still not a proper fix for this? I think that this issue should be re-opened.

**Comment by alcuadrado** [comment]
The only workaround I know works is using `import type {...} from "..."`, and running `TS_NODE_TRANSPILE_ONLY=1 npx hardhat compile`.

**Comment by alcuadrado** [comment]
Maybe this is something worth adding to the docs of the plugin, @krzkaczor

**Comment by mr13tech** [comment]
agree to reopen this

**Comment by sebastiantf** [comment]
i am facing this issue too. And this workaround fixes the issue.

> The only workaround I know works is using `import type {...} from "..."`, and running `TS_NODE_TRANSPILE_ONLY=1 npx hardhat compile`.

But I am using the `Contract__factory.connect()` method inside the task so importing the factory as a type breaks that

**Comment by marcelomorgado** [comment]
> i am facing this issue too. And this workaround fixes the issue.
> 
> > The only workaround I know works is using `import type {...} from "..."`, and running `TS_NODE_TRANSPILE_ONLY=1 npx hardhat compile`.
> 
> But I am using the `Contract__factory.connect()` method inside the task so importing the factory as a type breaks that

Yes, same here. The types are working fine but the same problem remains when trying to use `Contract__factory` classes on tasks.

FYI @alcuadrado @krzkaczor

**Comment by stoooops** [comment]
I am another person facing the same chicken and egg problem. Seems to make the generated types unusable in task definitions which means they can't be use for parameterized hardhat scripts. Cleaning your environment results in `hardhat` always failing due to missing imports.

**Comment by stoooops** [comment]
I have a large private monorepo that I unfortunately cannot share yet, but I do understand the build systems pretty well (famous last words).

I will see if I can fork the starter project and reproduce when I have time but it probably won't be for a couple weeks or longer. 

Thanks for the reply.

**Comment by alcuadrado** [comment]
Can you confirm that you are importing types and note values? For example by using `import type ...`.

Importing types should work in recent versions, while values is in fact a chicken-and-egg problem.
