### ISSUE TITLE
 Error: Transaction reverted: trying to deploy a contract whose code is too large

### ISSUE THREAD

**Issue by sriharikapu** [ethereum-ts/TypeChain#375]
I came across a scenario where I cant deploy the contract whose code is more than 3000 lines, while writing the tests

` Error: Transaction reverted: trying to deploy a contract whose code is too large`

Any thoughts on how to fix this

**Comment by quezak** [comment]
This is not a TypeChain issue -- we only generate typings for existing tools :) I see you've already created an issue in hardhat so I'll close this one.

**Comment by krzkaczor** [comment]
@quezak is right. Just to add: if you use ganache consider using: `allowUnlimitedContractSize` flag. But obviously, you still won't be able to deploy such big SC on the mainnet.

**Comment by sriharikapu** [comment]
Thanks then, this would be the issue from hardhat. `allowUnlimitedContractSize :true`  didn't work for me either

**Comment by quezak** [comment]
@sriharikapu another thing -- since your contract is over 3000 lines long, it may be that it *really* is too large to be deployed. Check the gas required to deploy it, if it's over the 12.5M block limit, you'll need to enable solidity optimizations or split it into smaller contracts.

**Comment by redigaffi** [comment]
allowUnlimitedContractSize is not working for me, the point of deploying without optimizations locally is to be able to debug properly. Optimization should only be used in mainnet...

**Comment by solchef** [comment]
settings: { optimizer: { enabled: true, runs: 200, details: { yul: false }, }, }
