### ISSUE TITLE
Event types

### ISSUE THREAD

**Issue by janklimo** [ethereum-ts/TypeChain#379]
Given this ABI:

```json
  {
    "name": "CheckpointToken",
    "inputs": [
      { "type": "uint256", "name": "time", "indexed": false },
      { "type": "uint256", "name": "tokens", "indexed": false }
    ],
    "anonymous": false,
    "type": "event"
  }
```

the generated type is

```ts
    CheckpointToken(
      time: null,
      tokens: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { time: BigNumber; tokens: BigNumber }
    >;
```

which only allows the following usage:

```ts
contract.filters.CheckpointToken(null, null)
```

As mentioned in [this comment](https://github.com/ethereum-ts/TypeChain/pull/321#issuecomment-785638289) `ethers.js` is fine accepting no arguments. I'm using the version `6.0.5` of the package and this isn't currently possible.

**Comment by zemse** [comment]
@janklimo Thanks for the reminder, I'll put this on my to-do list for this weekend.
