### ISSUE TITLE
Hardhat caching does not verify files are there/up to date

### ISSUE THREAD

**Issue by roderik** [ethereum-ts/TypeChain#381]
I upgraded to v5.

Ran compile which failed 

```
Generating typings for: 20 artifacts in dir: types/truffle-contracts for target: truffle-v5
Successfully generated 19 typings!
Compilation finished successfully
migrations/1_initial_migration.ts:1:10 - error TS2305: Module '"../types/truffle-contracts"' has no exported member 'MigrationsContract'.

1 import { MigrationsContract } from '../types/truffle-contracts';
```

Removed the types folder, ran it again

```
Nothing to compile
No need to generate any newer typings.
```

But the files were not there.
Removed the hardhat build and cache folder
Then it worked

```
Generating typings for: 21 artifacts in dir: types/truffle-contracts for target: truffle-v5
Successfully generated 20 typings!
Compilation finished successfully
```

So I think a) the first time it did not regenerate the index.d.ts and b) maybe some light checking if the files are actually there? Then again, it is just when upgrading, so maybe a notice in the changelog is enough?

**Comment by roderik** [comment]
hmmm, follow up compiles have the same issue

```
Generating typings for: 21 artifacts in dir: types/truffle-contracts for target: truffle-v5
Successfully generated 19 typings!
Compilation finished successfully
migrations/1_initial_migration.ts:1:10 - error TS2305: Module '"../types/truffle-contracts"' has no exported member 'MigrationsContract'.

1 import { MigrationsContract } from '../types/truffle-contracts';
           ~~~~~~~~~~~~~~

```

No changes to the Migrations contract, and the index.d.ts file does not contain it anymore, it does other contracts, also a new one that I just made.

**Comment by roderik** [comment]
I had to downgrade to keep my development flow. The caching keeps messing up on contract changes.

**Comment by krzkaczor** [comment]
Oh, right currently incremental generation is supported only in ethers target but still, this shouldn't misbehave.

I will work on a fix in a bit.

**Comment by nkuba** [comment]
@krzkaczor have you had a chance to work on this issue? I'm still experiencing the same problem with `"typechain": "6.0.4"` and `"@typechain/ethers-v5": "8.0.4"`.
