### ISSUE TITLE
Typecheck is failling in your truffle-v5 example

### ISSUE THREAD

**Issue by Ebernn** [ethereum-ts/TypeChain#385]
Hello,

I just cloned [your example](https://github.com/ethereum-ts/TypeChain/tree/master/examples/truffle-v5), and:

`npm i`

`npm run typecheck`

leads to:

```
$ npm run typecheck

> example-truffle-v5@0.0.1 typecheck
> tsc --noEmit

types/truffle-contracts/index.d.ts:4:9 - error TS2669: Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.

4 declare global {
          ~~~~~~

types/truffle-contracts/types.d.ts:17:34 - error TS2694: Namespace 'Truffle' has no exported member 'Artifacts'.

17 declare const artifacts: Truffle.Artifacts;
                                    ~~~~~~~~~


Found 2 errors.

npm ERR! code 2
npm ERR! path E:\projects\js\truffle-v5
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c tsc --noEmit

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bbern\AppData\Local\npm-cache\_logs\2021-05-16T22_52_45_541Z-debug.log
```

Did I miss a step or do something wrong? Thanks in advance.

___________
Specs: Windows 10 64bits v1909 ; npm v7.5.4

**Comment by krzkaczor** [comment]
Can you try using yarn? we run `typecheck` on CI so I am pretty sure it works. 

Maybe there was a truffle breaking change that broke Truffle.Artifacts

**Comment by Ebernn** [comment]
weird, I have the exact same error using yarn. What exact truffle version are you using on the CI?

**Comment by GolfredoPerezFernandez** [comment]
+1 same error

**Comment by krzkaczor** [comment]
To clarify, did you remove node_modules installed by npm and reinstall them using yarn?

Here's the CI config: https://github.com/ethereum-ts/TypeChain/blob/master/.github/workflows/ci.yml#L68

**Comment by Ebernn** [comment]
sure, I've cleaned up my folder using `npx npkill`, no `node_modules` was there before I ran `yarn`.
I'm still trying to figure out what is happening... 🤔

**Comment by EctoplasmFantom** [comment]
Problem seems to be the single quotes used in the generate-types script causing typechain to match 0 files which causes various other problems, including the error you've seen.  Changing the single quotes to double quotes allows it to match the files and the errors go away.  I'm assuming this is only a problem for Windows, and that's why this wasn't detected in CI.

**Comment by krzkaczor** [comment]
I am closing this for now as this is windows specific. 

I created: https://github.com/ethereum-ts/TypeChain/issues/411 and it's marked as help wanted :-> If you want to pick it up and add CI config for windows you have all my support. Thanks for reporting.
