### ISSUE TITLE
Support unnamed function parameters

### ISSUE THREAD

**Issue by ItsNickBarry** [ethereum-ts/TypeChain#389]
Functions with unnamed parameters cause an error when generating types.  See [here](https://github.com/solidstate-network/solidstate-solidity/pull/19#discussion_r639398139).

When a function is overridden and a parameter is not needed in the new function implementation, it is necessary to omit the variable name to prevent a Solidity compilation warning ("unused variable").  Is there  reason fundamental to TypeChain that parameters must be named?

**Comment by quezak** [comment]
@ItsNickBarry can you post a Solidity snipped that reproduces the issue?

**Comment by Lumyo** [comment]
> @ItsNickBarry can you post a Solidity snippet that reproduces the issue?

The issue occured when generating the types on this file : https://github.com/solidstate-network/solidstate-solidity/blob/master/contracts/signature/ERC1271Stored.sol

`_isValidSignature` has an unnamed parameter, which resulted in the following error :
![image](https://user-images.githubusercontent.com/7013086/119635678-826b7280-be46-11eb-9955-26ab2ca0d11f.png)
