### ISSUE TITLE
`npx hardhat clean` errors with `fs_extra_1.default.pathExists is not a function`

### ISSUE THREAD

**Issue by nichanank** [ethereum-ts/TypeChain#395]
Getting this error upon running `npx hardhat clean`
![image](https://user-images.githubusercontent.com/15038946/120958415-e7e22c00-c781-11eb-93fe-8da79142579b.png)

Relevant package versions:
@typechain/ethers-v5: ^7.0.0
@typechain/hardhat": ^2.0.1
hardhat: ^2.2.1

**Comment by krzkaczor** [comment]
A quick fix would be to install `fs-extra` locally. It seems like it's missing in our `package.json`.

**Comment by nichanank** [comment]
> A quick fix would be to install `fs-extra` locally. It seems like it's missing in our `package.json`.

this fixed it. thanks!
