### ISSUE TITLE
cannot read property outDir of undefined

### ISSUE THREAD

**Issue by aster2709** [ethereum-ts/TypeChain#401]
team, on running npx hardhat compile, I'm getting the error ```TypeError: Cannot read property 'outDir' of undefined```
----
here are my dependencies: 
![image](https://user-images.githubusercontent.com/39130640/121847949-fb077580-cd06-11eb-8979-3451d748e0e2.png)
----
here is my hardhat.config.ts:
![image](https://user-images.githubusercontent.com/39130640/121848091-2a1de700-cd07-11eb-9acd-8b3071a47ab0.png)
----
here is my tsconfig.json:
![image](https://user-images.githubusercontent.com/39130640/121848144-3dc94d80-cd07-11eb-9ccf-7642ef750f96.png)
----
on running ```npx hardhat compile```
![image](https://user-images.githubusercontent.com/39130640/121848224-5d607600-cd07-11eb-99f1-a38f82f13bab.png)
----
env: ubuntu lts, node lts, and latest npm

**Comment by aster2709** [comment]
on installing everything as regular dependencies, it worked. do you have a clue why? and lmk should I close this issue

**Comment by krzkaczor** [comment]
I am sure that it was a version mismatch. Probably you run older typechain core with the newest target (or the other way around).

**Comment by zen2see** [comment]
I had to clear clear my artifacts, cache and typechain directories, re-run npx hardhat compile.

**Comment by itinance** [comment]
For me this error happened after upgrading hardhat and typechain to most recent versions.

This is the diff of my rollback that solved the issue at the moment:

```
diff --git a/package.json b/package.json
index 37212a9..9d2ba6c 100644
--- a/package.json
+++ b/package.json
@@ -25,10 +25,10 @@
   "devDependencies": {
     "@nomiclabs/buidler": "^1.4.8",
     "@nomiclabs/hardhat-ethers": "^2.0.2",
-    "@nomiclabs/hardhat-etherscan": "2.1.6",
+    "@nomiclabs/hardhat-etherscan": "^2.1.1",
     "@nomiclabs/hardhat-waffle": "^2.0.1",
     "@typechain/ethers-v5": "^6.0.5",
-    "@typechain/hardhat": "2.3.0",
+    "@typechain/hardhat": "^1.0.1",
     "@types/chai": "^4.2.15",
     "@types/chai-as-promised": "^7.1.3",
     "@types/mocha": "^8.2.2",
@@ -38,15 +38,15 @@
     "chai-datetime": "^1.8.0",
     "ethereum-waffle": "^3.3.0",
     "ethers": "^5.0.31",
-    "hardhat": "2.6.4",
+    "hardhat": "^2.1.1",
     "hardhat-deploy": "^0.9.1",
     "hardhat-gas-reporter": "^1.0.4",
     "hardhat-typechain": "^0.3.5",
     "solidity-coverage": "^0.7.17",
     "ts-generator": "^0.1.1",
     "ts-node": "^9.1.1",
-    "typechain": "5.1.2",
-    "typescript": "4.4.3"
+    "typechain": "^4.0.3",
+    "typescript": "^4.2.4"
   },

```

**Comment by alxiong** [comment]
for me, running `hardhat clean` before `hardhat compile` solve the issue.

**Comment by sveitser** [comment]
And I sometimes need to `rm -r node_modules` and `pnpm i` :thinking:
