### ISSUE TITLE
ERESOLVE unable to resolve dependency tree while installing typechain @typechain/hardhat @typechain/ethers-v5

### ISSUE THREAD

**Issue by StErMi** [ethereum-ts/TypeChain#406]
Hi all,

I've tried to install like in the readme file with the command `npm install --save-dev typechain @typechain/hardhat @typechain/ethers-v5` and I've got this error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: typechain@3.0.0
npm ERR! node_modules/typechain
npm ERR!   typechain@"^3.0.0" from @ethereum-waffle/compiler@3.4.0
npm ERR!   node_modules/@ethereum-waffle/compiler
npm ERR!     @ethereum-waffle/compiler@"^3.4.0" from ethereum-waffle@3.4.0
npm ERR!     node_modules/ethereum-waffle
npm ERR!       peer ethereum-waffle@"^3.2.0" from @nomiclabs/hardhat-waffle@2.0.1
npm ERR!       node_modules/@nomiclabs/hardhat-waffle
npm ERR!         dev @nomiclabs/hardhat-waffle@"^2.0.1" from the root project
npm ERR!       1 more (the root project)
npm ERR!   peer typechain@"^3.0.0" from @typechain/ethers-v5@2.0.0
npm ERR!   node_modules/@typechain/ethers-v5
npm ERR!     @typechain/ethers-v5@"^2.0.0" from @ethereum-waffle/compiler@3.4.0
npm ERR!     node_modules/@ethereum-waffle/compiler
npm ERR!       @ethereum-waffle/compiler@"^3.4.0" from ethereum-waffle@3.4.0
npm ERR!       node_modules/ethereum-waffle
npm ERR!         peer ethereum-waffle@"^3.2.0" from @nomiclabs/hardhat-waffle@2.0.1
npm ERR!         node_modules/@nomiclabs/hardhat-waffle
npm ERR!         1 more (the root project)
npm ERR!     dev @typechain/ethers-v5@"*" from the root project
npm ERR!   1 more (the root project)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! dev @typechain/hardhat@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typechain@5.0.0
npm ERR! node_modules/typechain
npm ERR!   peer typechain@"^5.0.0" from @typechain/hardhat@2.0.2
npm ERR!   node_modules/@typechain/hardhat
npm ERR!     dev @typechain/hardhat@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/MY_WORKSPACE/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/MY_WORKSPACE/.npm/_logs/2021-06-21T21_07_39_358Z-debug.log
```

what should I do? the hardhat project is brand new

**Comment by krzkaczor** [comment]
As npm suggests, try with `--force`. It might be due to the dep conflict with waffle...

**Comment by StErMi** [comment]
Don't ask me why but the whole problem was because when I did npm install it installed old packages not compatible one with another

**Comment by chubbyavo** [comment]
> Don't ask me why but the whole problem was because when I did npm install it installed old packages not compatible one with another

I'm seeing the same error. How did you resolve the issue? To me, this looked like `@ethereum-waffle/compiler@3.4.0` would need to update its `@typechain/ethers-v5` version (or I need to use a lower version of typechain...).

**Comment by StErMi** [comment]
> > Don't ask me why but the whole problem was because when I did npm install it installed old packages not compatible one with another
> 
> I'm seeing the same error. How did you resolve the issue? To me, this looked like `@ethereum-waffle/compiler@3.4.0` would need to update its `@typechain/ethers-v5` version (or I need to use a lower version of typechain...).

just remove all the libraries, clean you npm_mobules and reinstall the using the latest one

**Comment by chubbyavo** [comment]
> > > Don't ask me why but the whole problem was because when I did npm install it installed old packages not compatible one with another
> > 
> > 
> > I'm seeing the same error. How did you resolve the issue? To me, this looked like `@ethereum-waffle/compiler@3.4.0` would need to update its `@typechain/ethers-v5` version (or I need to use a lower version of typechain...).
> 
> just remove all the libraries, clean you npm_mobules and reinstall the using the latest one

Hmm, I think the problem is that `@ethereum-waffle/compiler@3.4.0` is the latest version. I ended up just `force` installing and it worked fine. Thanks though!

**Comment by wwarodom** [comment]
I ended up with '--force installation' too!! Don't know that will it be affected for the rest.

**Comment by abazlinton** [comment]
`--force` alone didn't work for me. I'm using the latest hardhat (2.6.5) and latest typechain hardhat plugin (2.3.0).

But this article helped -

https://www.carlrippon.com/upgrading-npm-dependencies/

So I used `npm outdated` to investigate. Then -

```
npm install --force typechain@latest
npm install @typechain/ethers-v5@latest
```

So far so good :S...

@chubbyavo seem to have detected the source of the problem.
