### ISSUE TITLE
Cannot find module 'typechain/dist/TypeChain' 

### ISSUE THREAD

**Issue by Tinalst** [ethereum-ts/TypeChain#409]
'typechain/dist/TypeChain' doesn't exist in typechain(version 5.0.0) library.

My package.json list as follow:
```
"devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.2",
    "@nomiclabs/hardhat-waffle": "^2.0.1",
    "@typechain/ethers-v5": "^7.0.1",
    "@types/chai": "^4.2.19",
    "@types/mocha": "^8.2.2",
    "@types/node": "^15.12.4",
    "chai": "^4.3.4",
    "ethereum-waffle": "^3.4.0",
    "ethers": "^5.3.1",
    "hardhat": "^2.4.0",
    "hardhat-gas-reporter": "^1.0.4",
    "hardhat-typechain": "^0.3.5",
    "ts-generator": "^0.1.1",
    "ts-node": "^10.0.0",
    "typechain": "^5.0.0",
    "typescript": "^4.3.4"
  }
```

**Comment by quezak** [comment]
Can you send a minimal reproduction repo or at least full repro instructions?

**Comment by incrypto32** [comment]
@quezak  Im facing the same issue..
[Just compile this repo](https://github.com/incrypto32/hardhat-tut)

**Comment by incrypto32** [comment]
Ok this issue was because i still used the 'hardhat-typechain' which is no longer maintained i guess the new official one is @typechain/hardhat . I see that @Tinalst  also uses this one.

**Comment by krzkaczor** [comment]
Yes. hardhat-typechain was migrated to this repo. There is a deprecation note on the repo i believe.

**Comment by incrypto32** [comment]
> Yes. hardhat-typechain was migrated to this repo. There is a deprecation note on the repo i believe.

@krzkaczor  but the hardhat documentation still mentions the old package that's what's misleading people

**Comment by krzkaczor** [comment]
Oh, good to know. I will repoen this issue to remember to send PR to HH docs.

**Comment by krzkaczor** [comment]
Related: https://github.com/nomiclabs/hardhat/pull/1739
