### ISSUE TITLE
[how to?] how to integrate typechain generated build into a react project

### ISSUE THREAD

**Issue by StErMi** [ethereum-ts/TypeChain#410]
Hi all,

is there an example on how to use the generated code from typechain (I'm using the hardhat plugin of typechain) inside a react project that uses ethersjs?

I would love to see some basic example with contract get/set calls (public/payable) and how to listen to events.

Thanks!

**Comment by krzkaczor** [comment]
You probably don't want to use it with ethers. Just copy build artifacts like ABIs to your react repo, install typechain + ethers target and run it through CLI. You will get generated types. I don't have really an example with react but it should be different from: https://github.com/ethereum-ts/TypeChain/tree/master/examples/ethers-v5

**Comment by StErMi** [comment]
Sorry I didn't understand this part: 

> You probably don't want to use it with ethers

So even if I own both the contract and the web3 app I should only copy the abi on the web3 app and re-run the typchain build?

**Comment by krzkaczor** [comment]
agh, i meant "you don't want to use it with *hardhat* (plugin)" sorry.

So if your react app is in a separate repo, not with contracts, then the easiest is to simply copy ABIs and regenerate types in the new repo. If they are in the same repo you might want to try to reuse types across projects.

**Comment by StErMi** [comment]
Sorry for the noob question it seems that the generated files from hardhat are not "compatible" with typechain. When I try to do that the script says 

```
Error occured:  Not a valid ABI
Run with --show-stack-traces to see the full stacktrace
```

What do I need to do to generate valid ABI file from hardhat? or am I missing something to configure the command?

**Comment by zemse** [comment]
One way you can also consider is, to publish your smart contract repo containing the typechain output to npm. And in your react project, just import that.
