### ISSUE TITLE
Typescript - Conversion issue between "Contract" type and "Counter.sol" example 

### ISSUE THREAD

**Issue by ppedziwiatr** [ethereum-ts/TypeChain#416]
Error from WebStorm:
```
TS2352: Conversion of type 'Contract' to type 'Counter' may be a mistake because neither type sufficiently overlaps with the other.
If this was intentional, convert the expression to 'unknown' first.
Type 'Contract' is missing the following properties from type 'Counter': off, queryFilter, countDown, countUp, and 4 more.
```
Using Counter.sol and test from the example: https://github.com/ethereum-ts/TypeChain/tree/master/packages/hardhat#usage

![image](https://user-images.githubusercontent.com/84311757/123644106-59fbdd00-d825-11eb-9d33-92876288cc93.png)

**Comment by krzkaczor** [comment]
It's because of ethers version mismatch. Upgrade it and it should be fine. 

Releated: https://github.com/ethereum-ts/TypeChain/issues/330

If this doesn't help please reopen.
