### ISSUE TITLE
Library addresses interface in factories, are not human readable

### ISSUE THREAD

**Issue by Lumyo** [ethereum-ts/TypeChain#421]
When I am generating typechain classes for `ethers-v5`, for a contract using a library with external calls, the library name in the interface is not human readable.

![image](https://user-images.githubusercontent.com/7013086/124216392-c7ab5000-db28-11eb-9330-d0877e9e5efb.png)

In the tests of the implementation of this feature in #178 , library contract name was human readable (Which makes me believe this is a bug)

**Comment by quezak** [comment]
What do you use to compile your Solidity files? Can you attach a minimal reproduction? (Solidity file + its JSON file)

Different compilation methods may result in slightly different JSONs. As the issue you linked says, I've implemented the readable names if `evm.bytecode.linkReferences` is present in the JSON, maybe the format changed or other libraries don't add such properties.

**Comment by ItsNickBarry** [comment]
@quezak Latest Hardhat with `@typechain/hardhat`.

**Comment by quezak** [comment]
@ItsNickBarry can you provide a minimal repro? (solidity file + the generated json file) It might be that the library names are encoded in the JSON in a different way, or not at all.

**Comment by Lumyo** [comment]
@quezak Here is a minimal repo with the issue https://github.com/Lumyo/typechain-library-issue

`yarn install`
`hardhat compile`

**Comment by quezak** [comment]
Looks like this will be a simple extentsion for the exisitng logic -- the `linkReferences` object is there, just under a different path. @Lumyo would you like to prepare a PR for this? You'd need to look for the `linkReferences` object in a few places before using it in the `extractLinkReferences` call [here](https://github.com/ethereum-ts/TypeChain/blob/master/packages/typechain/src/parser/abiParser.ts#L337)

waffle artifact:
```
  "evm": {
    "bytecode": {
      "linkReferences": {
        "contracts/TestLibrary.sol": {
          "TestLibrary": [
            {
              "length": 20,
              "start": 109
            }
          ]
        }
      },
      "object": ...,
      "opcodes": ...,
      "sourceMap": ...
    },
  },
  "bytecode": "<regular code>__$bd883744d816fd16f92b10543f972238fe$__<more code>"

```

hardhat artifact:
```
  "bytecode": "<regular code>__$bd883744d816fd16f92b10543f972238fe$__<more regular code>",
  "linkReferences": {
    "contracts/TestLibrary.sol": {
      "TestLibrary": [
        {
          "length": 20,
          "start": 105
        }
      ]
    }
  },
```

**Comment by Lumyo** [comment]
The above PR solves my issue 
![image](https://user-images.githubusercontent.com/7013086/124506074-7edfe980-ddfd-11eb-95d2-517b6a13e7d6.png)

**Comment by krzkaczor** [comment]
Thanks! Released as: https://github.com/ethereum-ts/TypeChain/releases/tag/typechain%405.1.2
