### ISSUE TITLE
glob is not a function & couldn't find ethers-v5 

### ISSUE THREAD

**Issue by kiwi745** [ethereum-ts/TypeChain#422]
Whenever trying to generate typings for my artifacts with typechain I am getting: `TypeError: glob is not a function`.

My `package.json`:
```
"@typechain/ethers-v5": "7.0.1",
"@typechain/hardhat": "2.0.2",
"typechain": "5.0.0",
"typescript": "4.3.4"
```

**Comment by kiwi745** [comment]
After struggling for some time with this issue I realized that my dependencies were wrong.
What I did in order to solve it, was to grab the latest release [here](https://github.com/ethereum-ts/TypeChain/releases) and go to its commit files.

In there, I looked for the matching versions of the packages I needed:
* `typescript`: inside the `package.json` in the root directory, under devDependencies
* `typechain`: look for the version property in `packages/typechain/package.json`
* `@typechain/hardhat`: look for the version property in `packages/hardhat/package.json`
* `@typechain/ethers-v5`: look for the version property in `packages/target-ethers-v5/package.json`

I ended up with:
```
"typechain": "5.1.1",
"typescript": "4.1.5",
"@typechain/hardhat": "2.1.1",
"@typechain/ethers-v5": "7.0.1"
```

**Comment by krzkaczor** [comment]
Generally, you should be fine with all versions upgraded to the latest.
