### ISSUE TITLE
[hardhat plugin] The outdir config is resolved relative to the CWD and not the project root

### ISSUE THREAD

**Issue by alcuadrado** [ethereum-ts/TypeChain#431]
This was reported on discord:

> It seems that the typechain output is placed relative to the current work directory, i.e. if compile/test is run on anywhere but the root, the typechain directory will be created there. Adding outDir: './typechain' won't help as it stays relative to cwd.
> 
> Is that by design? Is there a way to avoid this and always place it into the project root?

**Comment by alcuadrado** [comment]
Here's an example of how to handle this properly:

https://github.com/nomiclabs/hardhat-ts-plugin-boilerplate/blob/ea6deb2f176e5442942bf9951258a32fbd589353/src/index.ts#L25-L40

**Comment by alcuadrado** [comment]
As workaround is using the absolute path in the config, for example, 

```js
`${__dirname}/typechain`
```
However, this leads to the absolute path being printed in the logs (i.e. `"Generating typings for: 35 artifacts in dir: <path>"`). I think this path would be nicer if it were relative from the CWD.

**Comment by krzkaczor** [comment]
Thanks for reporting this, this is clearly a bug.

**Comment by krzkaczor** [comment]
Thanks for reporting this. Fixed in: https://github.com/ethereum-ts/TypeChain/releases/tag/%40typechain%2Fhardhat%402.2.0

CC: @axic
