### ISSUE TITLE
Support for RxJS Observables

### ISSUE THREAD

**Issue by macbem** [ethereum-ts/TypeChain#47]
What do you think about implementing a switch that would allow the user to choose between RxJS Observables and Promises? It would make this lib a lot easier to use with Angular.

**Comment by Stradivario** [comment]
I will handle it ;) will introduce soon pull request anyway you can do Observable.fromPromise(promise)

**Comment by krzkaczor** [comment]
@StradivarioI hope you're aware of https://github.com/Neufund/TypeChain/pull/43. I want to merge soon. Sorry for the delay.

**Comment by krzkaczor** [comment]
@macbem @Stradivario events support was just merged and published as `0.2.0`. 

If you have some code snippets that we could place in documentation go ahead and enlighten us :)
