### ISSUE TITLE
Add docs with examples

### ISSUE THREAD

**Issue by eswarasai** [ethereum-ts/TypeChain#58]
As a developer, I'd like to see all the custom functions provided by TypeChain under the hood along with a sample code explaining their usage. One such example would be to watch for the events during a transaction.

**Comment by krzkaczor** [comment]
That's a valid point. It's on my todo list. I am gonna add more detailed in `examples` (non existing currently) directory and docs

**Comment by mrwillis** [comment]
+1 Would love some examples as I am new to TS with solidity! :)

**Comment by krzkaczor** [comment]
New version stops reinventing new API for wrappers, typechain style wrappers are still there (legacy target) but I expect most folks use `web3-1.0.0` or `truffle` targets (more coming soon) which just generates typings for existing APIs. 

Does this improve the situation?

**Comment by eswarasai** [comment]
Yes. I think upgrading to `web3-1.0.0` should resolve the need for additional documentation for TypeChain wrappers. Sorry for the delay in getting back and thanks a lot for adding support to the `web3-1.0.0` target :)

Also, feel free to close this issue if you feel like docs isn't priority at the moment but I highly recommend adding `examples` directory and also basic `docs` if possible down the road to help the community in getting started as well as understand how they can easily leverage the repo to generate appropriate typings. Thanks!

**Comment by krzkaczor** [comment]
@mrwillis here you have an example with truffle: https://github.com/ethereum-ts/truffle-typechain-example

@eswarasai yeah I will make examples more discoverable in the readme and close this for now.
