### ISSUE TITLE
Unable to use with factory contracts + truffle

### ISSUE THREAD

**Issue by mrwillis** [ethereum-ts/TypeChain#63]
Hi,

Awesome library by the way :)

I have this very weird error using truffle and a factory contract that creates other contracts. I've reproduced the error here: https://github.com/mrwillis/typechain-factory-repro. It is a very simple project.

Set up instructions are in the README. 

For some reason, when I change the visibility of the `problem` member in the created contract (`Dummy.sol`) to `public`, the transaction is unable to complete. I tried increasing the gas with `ganache-cli` to a very large amount as well as the `gas` setting in the truffle to no avail.

Any ideas? Is this a bug?

Thanks!

**Comment by mrwillis** [comment]
I'll note that it seems to do something with sendTransaction on Web3. If I just do the standard dummyContract.newDummy(... params) then there is no issue.

**Comment by mrwillis** [comment]
@krzkaczor Any ideas what this could be? Happy to submit a PR with a fix if we can figure it out

**Comment by krzkaczor** [comment]
@mrwillis Hey, sorry for the delay. I will take a look at it tmrw. Which is in 12h in my timezone ;D

**Comment by krzkaczor** [comment]
@mrwillis okay I reproduced it. Thanks for repo. This seems weird indeed. I am investigating it now.

**Comment by krzkaczor** [comment]
Okay I don't think that this is a TypeChain problem but I am not sure what is causing different bahaviour... 2 points:
- TypeChain treats separate contracts in total isolation. You call DummyFactory wrapper but changing Dummy contract makes tests pass. Meaning that wrapper code for DummyFactory is the same.

- Use `tx.getData()` to get real tx data. From what i see they are exactly the same in both cases (take into account that you use current time to create tx thus it can differ).

Could you try using truffle contracts directly or web3 to issue this call? What's the result?

**Comment by mrwillis** [comment]
I've tried using truffle contracts directly and it passes perfectly fine. Let me make another branch with the truffle transaction to show. It is bizarre.

**Comment by mrwillis** [comment]
Alright I just put it on the `master` branch. Runs fine with truffle contracts as shown. I also added a basic log. 

Maybe it's some arcane gas issue? This has got to be the weirdest thing I've ever seen haha

**Comment by krzkaczor** [comment]
I am on it, its really interesting case :D I tested it with Remix and it worked there. Soooo it might be a TypeChain / Web3.js issue in the end. 

Btw. protip for setting up the project — you don't have to require tsc installed globally just add it to your project as local dep.
