### ISSUE TITLE
Support stateMutability

### ISSUE THREAD

**Issue by axic** [ethereum-ts/TypeChain#65]
For close to a year now Solidity also outputs the `stateMutability` field for each function. This can have the following values:
- pure
- view
- nonpayable
- payable

For backwards compatibility also the field `constant` (set to true on `stateMutability` pure or view) and `payable` (set to true on `stateMutability `payable`) is present.

We'd like to phase out the `constant` and `payable` fields. For more see https://solidity.readthedocs.io/en/develop/abi-spec.html#json

It seems that `abiParser.ts` doesn't support it: https://github.com/Neufund/TypeChain/blob/master/lib/abiParser.ts#L47

**Comment by krzkaczor** [comment]
@axic thanks for your comment. I actually really like this new approach. I will work on improving it when i ll find some time.
