### ISSUE TITLE
TypeScript: 'interface' is a reserved word in strict mode

### ISSUE THREAD

**Issue by jacque006** [ethereum-ts/TypeChain#885]
### Versions

@typechain/ethers-v6: `0.5.1`
@typechain/hardhat: `9.1.0`
typechain: `8.3.2`
typescript: `5.3.2`

### Details

When Typescript [strict mode](https://www.typescriptlang.org/tsconfig#strict) is enabled & type definitions are generated for Solidity interfaces, the exported name of `interface` from the index file (`export * as interface from "./interface"`) fails as `inferface` is a reserved keyword in JS/TS.

Typecheck error (`tsc --noEmit`):
```
error TS1214: Identifier expected. 'interface' is a reserved word in strict mode. Modules are automatically in strict mode.

7 export * as interface from "./interface";
```

Example `index.ts` from our project that encounters issue (line 7):
```typescript
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as safeEcdsaPluginSol from "./SafeECDSAPlugin.sol";
export * as safeEcdsaRecoveryPluginSol from "./SafeECDSARecoveryPlugin.sol";
export * as compression from "./compression";
export * as interface from "./interface"; // <-- Line that causes issue
export * as utils from "./utils";
export { SafeCompressionFactory__factory } from "./SafeCompressionFactory__factory";
export { SafeCompressionPlugin__factory } from "./SafeCompressionPlugin__factory";
export { SafeECDSAFactory__factory } from "./SafeECDSAFactory__factory";
export { SafeZKPPasswordFactory__factory } from "./SafeZKPPasswordFactory__factory";
export { SafeZKPPasswordPlugin__factory } from "./SafeZKPPasswordPlugin__factory";
```

### Questions

Are there any known workarounds/solutions for this issue? ~~I will also try upgrading all typechain/ethers deps to latest in our project in case a fix was not in release notes.~~ Did not resolve

**Comment by krzkaczor** [comment]
The easiest way would be to rename your solidity contract/interface or add a simple script that will rename artifact (abi file) after build. It greatly depends on your setup. 

Note that the problem is not filename but rather `interface` symbol.
